### PR TITLE
Request to add Check Input Gestures add-on

### PR DESCRIPTION
**Pull request by grisov**
Find and fix input gestures conflicts in NVDA and add-ons. The general term "input gestures" includes keyboard commands, commands entered from Braille keyboards and gestures of touch screens.  
Each of the installed add-ons can make changes to the NVDA configuration by adding or reassigning existing input gestures. If the same input gestures are binded to several functions, it will be impossible to call some of them.  

## Search for duplicate gestures
To detect duplicate gestures, call the NVDA menu, go to the "Tools" submenu, then - "Check Input Gestures" and activate the menu item "Search for duplicate gestures...".  
After that, all input gestures used in NVDA will be checked in the following order:

1. globalCommands;
2. globalPlugins.

## Gestures without description
To view the list of gestures binded with functions without a text description, if they are found in your NVDA configuration, you need to call the NVDA menu, go to the submenu "Tools", then - "Gestures without description...".  
Such features do not appear in the standard NVDA "Input Gestures..." dialog, so it is not yet possible to delete or reassign associated gestures.

### CODE REVIEW

**Comment by nvdaes** [comment]
Hello. I'll review this PR on May 22, as proposed on this [Thread of the add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/message/15120), to give even more oportunities to provide feedback by the wide community before posting the add-on.

Just a question: in case you don't need to post a development version different to the stable add-on, if they are the same, please use the same URL for an easier review. We have to review the manifest and URL.

Thanks

**Comment by grisov** [comment]
ok, of course i agree to wait for feedback from the wide community.  

I also removed the link to the version in development 812fdbdb6e7433f87d0049 .

**Comment by nvdaes** [comment]
Thanks.

**Comment by nvdaes** [comment]
Hello. I'll approve this PR.

I noted something not affecting basic review at all: the title of the document showed in the add-on Help contains -dev subfix. This maybe related to the use of GitHub Actions and add-on template, but it shouldn't block mergeability of this PR.

Congrats!

Sha256: 54fdf6ffe00e80815e4e543f6a0d2864e2d3357e2d253a8334460a5c404f9f2f
Manifest is right.

@feerrenrut  , in case we should use standardized info for new add-ons and updates, let us know or a PR template maybe created if needed.

**Review by nvdaes — APPROVED** [review]

**Comment by grisov** [comment]
Thanks, it's great!  

Regarding the word "dev" in the ReadMe pages - I fixed this problem.  

Have a nice day! :)

**Pull request merged**
