### PR TITLE
Updated Calibre stable and development versions

### PR DESCRIPTION
**Pull request by jmdaweb**
Updated Calibre stable to version 2.2, and development version to dev210327. They include several bug fixes. In addition, the development version brings experimental support for Calibre ebook viewer.
CC @javidominguez

### CODE REVIEW

**Comment by javidominguez** [comment]
thanks @jmdaweb for making the pull request for me, I didn't know how addon files update now.  This version has very small but important changes for users of the latest versions of NVDA.  barely two lines change but without them an important part of the addon does not work.

**Review by feerrenrut — APPROVED** [review]
Changes look fine, but there are now conflicts that need to be resolved.

**Comment by jmdaweb** [comment]
There was a conflict caused by latest commits to Character Information. Now it is fixed.

**Review by feerrenrut — APPROVED** [review]
Thanks @jmdaweb

**Pull request merged**
