### PR TITLE
Update of dayOfTheWeek, mp3DirectCut and sayCurrentKeyboardLanguage dev download link (21.09-dev)

### PR DESCRIPTION
**Pull request by abdel792**
### This PR includes the following changes:

The update of the development download link to 21.09-dev of the following add-ons:

1. dayOfTheWeek;
2. mp3DirectCut;
3. sayCurrentKeyboardLanguage.

### CODE REVIEW

**Comment by nvdaes** [comment]
Dear Abdel, please fill in the template and make a pull request for each add-on. We have to review the URL and manifest for each one and a template, according to common practices for PRs on this repo, is provided to make reviews easier. Thanks

**Comment by abdel792** [comment]
Dear @nvdaes,

The PR are here :

1. [dayOfTheWeek](https://github.com/nvdaaddons/dayOfTheWeek/pull/1);
2. [mp3DirectCut](https://github.com/nvdaaddons/mp3DirectCut/pull/2);
3. [sayCurrentKeyboardLanguage](https://github.com/nvdaaddons/sayCurrentKeyboardLanguage/pull/1).

For the last one, I couldn't send the PR to the master branch, I sent it to stable.

**Comment by abdel792** [comment]
Hi dear @nvdaes,

I'll close this PR and create 3 new ones, with PULL_REQUEST_TEMPLATE_MD content in the comment for each add-on.

Thanks.

**Comment by nvdaes** [comment]
Ok, I"ll review them. Yesterday I changed my computer and I had difficulties to know where was the power button, which is a key on the keyboard, and I"m installing programs and configuring things, but I expect to review it this weekend.

**Pull request closed without merging**
