### PR TITLE
Kill NVDA 0.2

### PR DESCRIPTION
**Pull request by josephsl**
### Release information
- Name: Kill NVDA
- Author: Tyler Spivey
- Repo: https://github.com/tspivey/killNVDA
- Version: 0.2
- Update channel: stable
- NVDA compatibility: 2019.2 and beyond
- Sha256: 8c1b01b8666cec2fe8d51680846c1d5f61c9f9cc1563186f41a956292807743a

### Additional information
CC @TSpivey

### CODE REVIEW

**Review by nvdaes — COMMENTED** [review]
Hello:

@sergiogomez31 reported that the add-on didn't work for him in this [thread about KillNVDA](https://nvda-addons.groups.io/g/nvda-addons/topic/84371664#16275)

Has this been clarified/fixed?

Kind regards

**Comment by sergiogomez31** [comment]
When I click on Kill NVDA there, nothing is executed, the menu closes, and
NVDA reads the safe screen again.

**Comment by CyrilleB79** [comment]
@sergiogomez31 was the previous version of this add-on working with NVDA 2020.4 on the same computer?
If not (i.e. if it is not a regression), I would advise to release this version of the add-on in any case for all the people for which the add-on is working.
The final decision is of course for NVAccess but it seems to me a legitimate argument.

**Comment by sergiogomez31** [comment]
Hi there!

The plugin was working for me on NVDA 2020.3, on NVDA 2020.4 it stopped
working, on all three computers.

Greetings

**Comment by tspivey** [comment]
It looks like this is a problem with Sergio's machine. I tested it myself and had others test it, and it works. I think it should be released, and if I ever figure out what this is I can update it with a fix.

**Review by nvdaes — APPROVED** [review]
OK. Hope Sergio's issues can be fixed in his machine or in a later update of this add-on.
Thanks

**Comment by sergiogomez31** [comment]
Hello!

Thank you very much Tyler! For my part, I will continue to test

Greetings

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
