### PR TITLE
Updating Tony's add-ons

### PR DESCRIPTION
**Pull request by mltony**
Second attempt. CC: @josephsl.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Folks should consult an older PR for details on add-on releases.

Thanks.

**Review by josephsl — APPROVED** [review]

**Comment by CyrilleB79** [comment]
@mltony there is a conflict on get.php. I think NVAccess expects to have no conflict before proceeding to the merge. I guess they expressed also their preference for independant PRs (one per add-on). Do you intend to make one ore both modifications in order to have your add-ons available on the website?
Since they do not seem to work so frequently on this repo, I recommend you to make the modifications when possible, in order to get PRs ready when they have a look at this repo again.

**Comment by mltony** [comment]
A lot of work to create ten separate pull requests. I guess I'll have to 
wait until everyone else is done updating their add-ons for the new 
version - otherwise too many conflicts and I am hit hard because I have 
10 entries there. Probably will try again later.

**Comment by XLTechie** [comment]
> A lot of work to create ten separate pull requests. I guess I'll have to

A bit of work to create them, yes, unless you have the gh tool available 
or want to install it.

But for keeping them updated with master easily, you can do the below.

checkout your fork of the addonFiles repo, then:

At a Windows command prompt:

cd addonFiles
git checkout master
git pull
for %a in (addonName1 addonName2 ... addonName10) do (
git checkout %a
git pull
git rebase master
git push -f
)

I suggest doing the latter in a batch file though, in which case replace 
both "%a" with "%%a".

- Or -

At a unix commandline (WSL, for example):

cd addonFiles
git checkout master
git pull
for addon in addonName1 addonName2 ... addonName10; do
git checkout "$addon"
git pull
git rebase master
git push -f
done

I don't guarantee this covers all possible difficulties, but I believe it 
should work.

You might also want some -q options to make git quieter.

HTH

**Comment by mltony** [comment]
I tried git rebase and it didn't work as intended in my case - for some 
reason it would create a lot of fake commits. But yeah, I was thinking 
that I'd need to write some kinds of scripts to send PRs automatically 
given how many conflicts with this get.php file.

**Comment by feerrenrut** [comment]
I can recommend the tool [gh cli](https://github.com/cli/cli/releases) made by GitHub for making the process easier if you are more comfortable on the command line.

I'll fix the conflicts in the file now, `rebase` allows you to create a linear history, but it is simpler to just merge in master:
```
git merge origin/master
```
Then resolve conflicts. There are a variety of ways to resolve conflicts, and preferences can be fairly personal. If you aren't confident on it I recommend following a few tutorials

**Pull request merged**
