### PR TITLE
ObjPad 21.04.1

### PR DESCRIPTION
**Pull request by josephsl**
## Release information:

* Name: ObjPad
* Author: Joseph Lee
* Repo: https://github.com/josephsl/objpad
* Version: 21.04.1
* Update channel: stable
* NVDA compatibility: 2020.1 and later

Changelog: emergency update to support NVDA 2021.1 changes.

Update: 21.04.1 replaces 21.04 with manifest changes (see below discussion).

### CODE REVIEW

**Comment by feerrenrut** [comment]
The metadata / readme for this is also incorrect. Please wait for the beta before claiming compatibility with 2021.1, and please update the last tested API version to the most recent (post beta) version of NVDA you have tested the addon with, this is likely 2020.4.

**Comment by josephsl** [comment]
Hi, will do so in the morning. Thanks.

**Comment by josephsl** [comment]
Hi,

Actually, all done now - build vars/metadata and readme updated.

Thanks.

**Comment by feerrenrut** [comment]
Ok. But you'll need to do a new release and update the URL in this PR.

**Comment by josephsl** [comment]
Hi, I already have, which involves creating commits that revert last tested version change, creating a new release based on this change, and uploading the new artifact to the add-on repo’s release page, which involve no change to PR at all. Thanks.

**Comment by feerrenrut** [comment]
I looked at: https://github.com/josephsl/objPad/compare/20.01...21.04

**Comment by feerrenrut** [comment]
I looked at: https://github.com/josephsl/objPad/compare/20.01...21.04

**Comment by josephsl** [comment]
Hi, ah, that makes sense – I can designate latest master branch commit as 21.04, or create 21.04.1 package. I guess the simplest solution would be 21.04.1 installer package while keeping 21.04 tag. Thanks.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
