### PR TITLE
easyTableNavigator V2.3

### PR DESCRIPTION
**Pull request by CoBC**
### Release information
- Name (Example, Add-on Updater): 
Easy Table Navigator
- Author (example, Your Name): 
Corentin Bacqué-Cazenave, Joseph Lee
- Repo (example, https://github.com/yourname/addonName): 
https://github.com/CoBC/easyTableNavigator-1
- Version (example, 21.07): 
2.3
- Update channel (example, stable, dev or stable and dev): 
Stable
- NVDA compatibility (example, 2021.1 and beyond): 
2019.3 and beyond

### Changelog (mention changes in separate lines starting with dash space)
* It is now possible to disable table navigation layer from everywhere
* Compatibility with NVDA 2022.1

### CODE REVIEW

**Review by nvdaes — CHANGES_REQUESTED** [review]
Hello, we cannot approve this PR since last tested version is set to 2022.1 and the beta for 2022.1 has not been released.

**Comment by CyrilleB79** [comment]
One thing to note:
The add-on's repo indicated in this PR is:
https://github.com/CoBC/easyTableNavigator-
But in `get.php` it is:
https://github.com/oreonan/easyTableNavigator-

Trying to access oreonan's GitHub's account redirects to CoBC's account. Thus, I think it is due to a GitHub username modifications. @CoBC do you confirm this change.

In any case, for now, there is no issue with links containing oreonan instead of CoBC; I don't know if there is a time limit to this redirection in GitHub.

**Comment by CoBC** [comment]
Tested with 2022.1Beta1, working as expected.

**Comment by CyrilleB79** [comment]
Did you test with tables in Word?
On my side it does not work with UIA enabled (see https://github.com/CoBC/easyTableNavigator-1/issues/6). This is not new. But since NVDA 2022.1 now enables UIA by default for recent versions of Word, this issue may become more visible and problematic.

Also a detail: The version in the Add-on manager is "v2.3" whereas it was "2.x" before (without the "v").
It's probably not a problem but I wonder why you have changed the versioning scheme and if it was intentional since you write "2.3" in this PR's description, not "v2.3".

**Comment by CyrilleB79** [comment]
Additional note:
Depending on if you plan to fix https://github.com/CoBC/easyTableNavigator-1/issues/6 quickly or not, you may follow the following path:
* release the v2.3 now without the UIA fix but with only the 2022.1 compatibility and release later a v2.3.1 with the UIA fix
* release later a release with both fixes (compatibility with 2022.1 and UIA)
You may choose either option, but it would be nice that you clarify here which one you choose.

Additional note 2:
If you make another release with UIA fix, do not forget translations since there has been new translations just merged today in the nvdaaddons repo.

**Comment by CyrilleB79** [comment]
Also another error: https://github.com/CoBC/easyTableNavigator-1/issues/7. This one is easy to fix.
So I think that at a v2.3.1 containing at least a fix for https://github.com/CoBC/easyTableNavigator-1/issues/7 and the last translations would be suitable for the community website.

**Comment by CoBC** [comment]
I'll fix the new issue, update translations and open a new PR. For the first issue you created I have to continue investigations, I don't see the cause of the issue for now.

**Pull request closed without merging**
