### PR TITLE
Access8Math 3.0

### PR DESCRIPTION
**Pull request by tsengwoody**
Access8Math 3.0 update

### CODE REVIEW

**Review by nvdaes — COMMENTED** [review]
Hello @tsengwoody , thanks for creating this PR. I can approve and request a review if you want: manifest and URL are right.

However, you may want to address some suggestions before posting this version to the website:

- For me is difficult to find the settings dialog of the add-on. Finally I have found it in the tools menu. is this enough clarified in the documentation? I don't find that settings can be find under Tools, and I would expect that they can be found under Preferences, Options, unless you explicitly reflect this fact.
-Supporting profiles for different languages is very easy. In the documentation, for me it's not easy to know if this is or not supported. Would you like to make these improvements before posting the add-on on the website, or should I approve this PR like that?

Also, usually we post download links at the start of readmes for the website. Would you like to do this as well?

Thanks for your reply.

**Comment by tsengwoody** [comment]
I updated the content of the file to explain the location of the Access8Math menu and change Multi-language custom settings section title  to localization.

**Comment by XLTechie** [comment]
I would agree with @nvdaes. Settings in the tools menu is very unexpected. 
That's what the preferences menu is for. Usually a subcategory of 
preferences > settings, but at least Preferences itself.

I wouldn't fail UX over it, but I don't think any user would expect that.

Note that I haven't tested the add-on; I am commenting based on @nvdaes 
review.

**Comment by tsengwoody** [comment]
From overall view, I think Access8Math is a tool.
Access8Math menu may not only have the preferences setting function, there may be other functions, like the current writing menu, it is not the setting function.

**Comment by josephsl** [comment]
Hi, we can argue that NVDA Remote Support follows this add-on’s user experience as well. We don’t have a set standard as to where settings can be found, relying on common sense from add-on developers and their justifications. Thanks.

**Review by nvdaes — APPROVED** [review]
Thanks. I'll approve this. I think you don't have access to SVN repo, which controls the documentation on the website. So, unless you want to do it yourself, I'll update the webpage for this add-on after this PR is merged, including a download link like done in other add-ons.

**Pull request merged**
