### PR TITLE
Windows 10 App Essentials 21.04

### PR DESCRIPTION
**Pull request by josephsl**
## Release information:

* Name: Windows 10 App Essentials
* Author: Joseph Lee, Derek Riemer and contributors
* Repo: https://github.com/josephsl/wintenapps
* Version: 21.04
* Update channel: stable
* NVDA compatibility: 2020.3 to 2020.4

Changelog: Calculator bug fixes.

Thanks.

### CODE REVIEW

**Review by feerrenrut — CHANGES_REQUESTED** [review]
The lasttested version in the manifest for this addon is 2021.1 please wait until the beta is released (and the API version is officially updated). There are still breaking changes going into the API.

**Comment by nvdaes** [comment]
The manifest contain fields not described in the developer guide, but I think they can be allowed since the add-on may use them and they aren't harmful:

>>

> minimumWindowsVersion = 10.0.19041

> updateChannel = None

**Comment by josephsl** [comment]
Hi, specifically, Add-on Updater uses these fields, and they are specified in the ad-on store manifest schema except for minimum Windows version (if I remember correctly). Thanks for reviewing this.

**Comment by nvdaes** [comment]
> 
> Hi, specifically, Add-on Updater uses these fields, and they are specified in the ad-on store manifest schema except for minimum Windows version (if I remember correctly). Thanks for reviewing this. 

Yes, beta can be specified in the json schema for the add-on store. Let us know when the add-on with correct manifest is ready to request a review from Reef

**Comment by josephsl** [comment]
Hi, it is ready as is. Thanks.

**Comment by josephsl** [comment]
Hi, I thought the last one submitted had the correct last tested version in the manifest – may need to check it again from my end. Thanks.

**Comment by josephsl** [comment]
Hi,

You're right - uploading a new release (also titled 21.04) that has the correct manifest info (thankfully the source code tag is correct).

Thanks.

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Thanks @josephsl. I've approved this PR and request a review from @feerrenrut.

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
Thanks @nvdaes and @josephsl

**Pull request merged**
