### PR TITLE
InstantTranslate v4.4.2 release

### PR DESCRIPTION
**Pull request by beqabeqa473**
AddonName: InstantTranslate
Authors: Alexy Sadovoy aka Lex, ruslan, beqa Gozalishvili, Mesar Hameed, Alberto Buffolino and other NVDA contributors
Version: 4.4.2
NVDA compatibility: 2018.3 and up
RepoURL: https://github.com/nvdaaddons/instanttranslate

### CODE REVIEW

**Comment by nvdaes** [comment]
@beqabeqa473, can you provide release information such as repo in case someone needs to create issues and other useful data for reference?
Thanks

**Comment by beqabeqa473** [comment]
hello.

where i should put it on?

thanks.

On 7/2/21, nvdaes ***@***.***> wrote:
> @beqabeqa473, can you provide release information such as repo in case
> someone needs to create issues and other useful data for reference?
> Thanks
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/addonFiles/pull/114#issuecomment-873175171


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by nvdaes** [comment]
Hello, in your next comment you can put for example: repo: https:\\... And the repo to create issues, and other drelevant data like Minimum vNVDA version compatible or other things that you consider useful to review. I"ll approve this tomorrow, now not in PC.

**Comment by CyrilleB79** [comment]
You may take example on other PRs in this repo, e.g. @nvdaes's ones.

**Review by nvdaes — APPROVED** [review]
I'll approve this now since URL and manifest are valid. Anyway, I recommend to provide more info on this PR for reference, like done in other pull requests.

According to my review, the add-on is compatible with NVDA 2018.3 and beyond, including 2021.1.

**Comment by nvdaes** [comment]
Info about name, repo and compatibility range is provided, seeing now. I hadn't read this before used to see it in a list, apologies.
@feerrenrut, let us know if we should create a template for pull requests to standardize info and format in case the probable delay to see the store is long.
Thanks

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
@nvdaes please feel free to open a PR against this repository to add anything that will help the review process.

**Comment by nvdaes** [comment]
OK @feerrenrut. I"l propose a pr template. Of course GitHub Actions maybe use to create pull request from issues avoiding forks, as I have tested in personal repos (not with addonFiles), but tfor now I"ll added a template and later will see.

**Comment by nvdaes** [comment]
Finally I'll propose an issue form so people can fill in with the
download url, and GitHub Actions should create a pr modifying get.php
and a bot should comment providing add-on info. Then a reviewer can
approve it with a label or something and the pr will be created.
The reason to make this proposal first is that pr templates don't
allow to use forms and, if the purpose is to fix format and we want
lists, people may not fill the template properly and the format
placing cursor after dashes may not be correct.

2021-07-06 5:52 GMT+02:00, nvdaes ***@***.***>:

**Pull request merged**
