### PR TITLE
Timezone 3.00

### PR DESCRIPTION
**Pull request by josephsl**
Note: posting on behalf of the author.

### Release information
- Name: Time Zoner
- Author: Munawar Bijani
- Repo: https://github.com/munawarb/NVDA-Time-Zoner
- Version: 3.00
- Update channel: stable
- NVDA compatibility: 2021.1 and later

### Changelog (mention changes in separate lines starting with dash space)
- Compatible with NVDA 2022.1

### CODE REVIEW

**Review by nvdaes — COMMENTED** [review]
@munawarb
I've seen your add-on very quickly and I don't see a terminate method to remove the settings panel. This is very easy to implement, so I wonder if you want us to approve this PR, or if you prefer to fix this, since we're just starting the beta fase of NVDA.
If you want, I can approve this and request a review from Reef (NV Access). Just asking. 😄

**Comment by CyrilleB79** [comment]
Also, is there a reason why the add-on is compatible only with 2022.1 (not below).
If this PR is merged before 2022.1 stable, there may be strange results:
A person who runs NVDA 2021.3.4 (last stable version) and who wants to install this add-on will download it from the community website but will be an incompatible add-on (2022.1+ required)

If add-on updater is updated accordingly, will it offer to v3.00 for people running NVDA 2021.3.4?

**Comment by munawarb** [comment]
Hi @nvdaes, Thanks for the feedback. I'm not familiar with the terminate method that I need to call. Is there documentation somewhere on this that I can look at? Thanks so much!

@CyrilleB79 good point. I'll fix this. There are no breaking changes so this version is compatible with earlier versions.

**Comment by nvdaes** [comment]
Hello:

You may look at the globalPluginHandler.GlobalPlugin class included in
NVDA's source code, where I'm reading now the following:

> 	def terminate(self):
		"""Terminate this global plugin.
		This will be called when NVDA is finished with this global plugin.
		"""


For example, I use this in clipContentsDesigner add-on:

	def terminate(self):
		NVDASettingsDialog.categoryClasses.remove(AddonSettingsPanel)

https://github.com/nvdaes/clipContentsDesigner

Note: esterday I created issue 10 on your repo about this.
Hope this helps

2022-03-25 11:02 GMT+01:00, Munawar Bijani ***@***.***>:

**Comment by munawarb** [comment]
Thanks so much for your help. I've updated my code. Should I make a new pull request @josephsl or will you update this one? Same version and everything, I just re-released under version 3.00.

**Comment by josephsl** [comment]
Hi, if the link remains the same, then there’s no need for another PR. Thanks.

**Comment by CyrilleB79** [comment]
Hi @munawarb

Did you change the compatibility following https://github.com/nvaccess/addonFiles/pull/278#issuecomment-1078424971 or not?
You have to options:
- make the add-on compatible with 2021.3 as well as with 2022.1.
- keep the version 3.00 compatible only with 2022.1 and above.
My personal preference goes to option 1.
Anyway if you choose the second option, I would recommend that this PR be not accepted and merged before NVDA 2022.1 stable is released.
Alternatively, you could put a download link to download the last version compatible with NVDA 2021.3. But I feel it is not worth it.

At last, as a tester, I would prefer that add-on authors use a new version number (e.g. 3.01)  and thus a new download link. Because there has been two versions 3.00 in the loop, the initial one and one with the `terminate` method fix.

**Comment by nvdaes** [comment]
Hello: I wanted to clarify that I"m looking some add-ons quickly in case it"s needed to fix security issues, since NVDA is taking care about this. Also, I agree with Cyrille about releasing different versions when code changes. Personally, for my add-ons, some of them compatible with NVDA 2022.-1 and beyond since I am not interested in supporting older versions making the code less readable, I think that I"ll create pull requests in addonFiles when NVDA publishes a release candidate, so when stable version is published these PRs have been reviewed and merged. Waiting for the stable version of NVDA can produce a delay or gap, a period of time with add-ons not updated on the website.

Enviado desde mi iPhone

**Comment by munawarb** [comment]
Hi,

Sure, I will update to 3.01. Yes, I have fixed the compatibility to make 
it compatible with 2021.3 and 2022.1.

**Comment by josephsl** [comment]
Hi, I can go ahead and change the link, or create a new PR. I think it might be easier to do the second option. Thanks.

**Comment by munawarb** [comment]
Sure. Thanks so much for doing that.

**Comment by nvdaes** [comment]
Hello: I think we can approve this. Anyway, after looking the terminate method and testing reloading plugins and setting NVDA in secure mode, though I don't have exact steps to reproduce, I get this error.

ERROR - scriptHandler.executeScript (22:29:04.149) - MainThread (7584):
error executing script: <bound method GlobalPlugin.script_sayNextTimezone of <globalPlugins.timezone.GlobalPlugin object at 0x0094E070>> with gesture 'alt+NVDA+flecha abajo'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 212, in executeScript
  File "C:\Users\nrm19\AppData\Roaming\nvda\addons\timezone\globalPlugins\timezone.py", line 387, in script_sayNextTimezone
    self.stopLastSpeakThread()
  File "C:\Users\nrm19\AppData\Roaming\nvda\addons\timezone\globalPlugins\timezone.py", line 349, in stopLastSpeakThread
    if self.lastSpeechThread is not None:
AttributeError: 'GlobalPlugin' object has no attribute 'lastSpeechThread'
I'm not sure what is causing this. Anyway, in the terminate method try... except... aren't used, and in secure mode the settings panel won't be added, but terminate will try to remove it. Maybe that     self.lastSpeechThread is not created and then the plugin tries to use it?

You may want to see this PR, where I use code created by @CyrilleB79 and @lukaszgo1 to disable plugins in secure mode properly.

https://github.com/nvdaes/readFeeds/pull/33

Anyway let me know if I should approve this like that without more changes.

**Comment by munawarb** [comment]
Hi @nvdaes,
Sorry, I sent my reply through email but I see now it didn't post here. You're correct re: secure mode. This error will happen because I create the attributes after first checking if we're in secure mode or not. I've blocked the scripts from running at all now if in secure mode. I've updated the add-on and created a new pull request to address these issues in #289.

**Comment by josephsl** [comment]
Hi,

Superseded by #289, closing.

**Pull request closed without merging**
