### PR TITLE
Request to add an Unmute add-on to the comunity website

### PR DESCRIPTION
**Pull request by grisov**
Add the Unmute add-on to the community website according to the fact that it has successfully passed the basic review.

### CODE REVIEW

**Comment by nvdaes** [comment]
@grisov, can you please create  a separate pull request for the unmute add-on? I want to approve both pull requests, the corresponding to checkInputGestures and the corresponding to the unmute add-on. But both add-ons (manifest and url) have to be reviewed separately and it's cleaner, and so we can avoid that one add-on blocks the other one.
Tomorrow I'll approve both PR.

Thanks.

**Comment by grisov** [comment]
ok, I'm reverted last commit here

**Comment by nvdaes** [comment]
Oh, you closed the PR. Don"t worry, I"m testing a bit more your two add-ons and I can reopen and approve this tomorrow if it"s related just to unmute. Sorry the inconveniences. I just like to do things in the cleaner and better way. Thanks a lot for your work

Enviado desde mi iPhone

**Comment by grisov** [comment]
Oh, sorry Noelia,  

This is due to my inexperience in using Git.  

I wanted to cancel the extra commits, but instead I closed PR.  

Now I have synchronized this branch and added only the necessary commit.  

I hope this time I did everything right :)  

Thank you and good luck!

**Review by nvdaes — CHANGES_REQUESTED** [review]
Please, remove the link to checkInputGestures add-on and add the unMute add-on link: https://github.com/grisov/Unmute/releases/download/latest/unmute-1.5.4.nvda-addon

**Comment by grisov** [comment]
Done ☺️

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Basic review: pass

- [Reference thread in add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/topic/77176470)
- [Additional review on GitHub](https://github.com/grisov/Unmute/issues/27)
- SHA256: d210f377a35394e3c5f6844c261982482d38e29251e21a5578afad476e52b8f9

**Comment by grisov** [comment]
I'm closing this pull request due to the creation of another #78 .

**Pull request closed without merging**
