### PR TITLE
Add Quick Notetaker

### PR DESCRIPTION
**Pull request by mohammad-suliman**
### Release information
- Name (Example, Add-on Updater): Quick Notetaker
- Author (example, Your Name): Eilana Benish, Mohammad Suliman
- Repo (example, https://github.com/yourname/addonName): https://github.com/mohammad-suliman/quickNotetaker
- Version (example, 21.07): 1.0
- Update channel (example, stable, dev or stable and dev): stable
- NVDA compatibility (example, 2021.1 and beyond): 2019.3 and later

### Changelog (mention changes in separate lines starting with dash space)

This is the first release! Hope you will enjoy it! Stay tuned for new features in the next releases.

### Additional information

The Quick Notetaker add-on is a wonderful tool which allows writing notes quickly and easily anytime and from any app the user is using. Whether the user is watching a video for example, or participating in a meeting on Zoom, teams or Google meet, they can easily and smoothly open the notetaker and take a note. In order to create a quick note, NVDA + Alt + n key combination can be used, a floating window appears at the top left corner of the screen, so the note can be typed there.
Every note that is being Created can optionally get the active window title, and as such, the note content can get the context in which this note was created by having the note title as the active window title the user was using. This behavior can be changed from the add-on settings, where the user can decide whether the active window title is captured when creating a new note.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, can you tell us more about the add-on, and if folks had a chance to look at it, a link to the relevant discussion thread on a forum such as NVDA add-ons list please? Thanks.

**Review by nvdaes — CHANGES_REQUESTED** [review]
@mohammad-suliman, can you attach the .nvdaaddon file to a release on GitHub, and provide a full URL starting with https and ending with .nvda-addon to review it? You can remove the binary .nvda-addonn from addonFiles repo and provide a link to GitHub.
Also, please place the id of this add-on in alphabetic order, not after zoom enhancements add-on, for consistency with practices followed here.
Thanks.

**Comment by mohammad-suliman** [comment]
Thank you @nvdaes ! I have addressed all requests except attaching the add-on file to the PR. GitHub doesn't support this. Have you meant something else? Or am I missing how to do this?

**Comment by nvdaes** [comment]
Hello, you can attach the nvda-addon on your releases. Please see an
example like:

https://github.com/nvdaes/clipContentsDesigner

You may use GitHub Actions for this if you want. The mentioned example
has some Github workflows that you may use and modify for your add-ons

2021-10-07 8:20 GMT+02:00, mohammad-suliman ***@***.***>:

**Review by nvdaes — APPROVED** [review]
Thanks @mohammad-suliman 
I'm approving this. Let us know if you need help to add the add-on documentation to the website when this PR is merged, or if you can do it yourself.
On the website, we can add a download link and make the format consistent with other add-ons.

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
