### PR TITLE
Update Windows Magnifier add-on

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Release information
- Name (Example, Add-on Updater): Windows Magnifier
- Author (example, Your Name): Cyrille Bougot
- Repo (example, https://github.com/yourname/addonName): https://github.com/CyrilleB79/winMag
- Version (example, 21.07): 2.0-dev-20220417
- Update channel (example, stable, dev or stable and dev): dev
- NVDA compatibility (example, 2021.1 and beyond): 2018.3 and beyond

### Changelog (mention changes in separate lines starting with dash space)

- The view can be moved with arrows while in Windows Magnifier layer.
- Capability to keep the Magnifier commands Window always on top or not.
- Added "Report screen edges" feature.
- Volume setting of tones when using move view commands.
- Reporting view moves and mouse to view commands are now supported in Lens mode.
- Compatibility with NVDA 2022.1.
- Fixed a bug that sometimes incorrectly reported that the Magnifier was not working upon script call.
- The release is now performed thanks to a GitHub action instead of appVeyor.
- Updated localizations.

### Additional information

Updated after releasing new dev version: link updated in get.php and initial description of PR updated.

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]

**Comment by CyrilleB79** [comment]
Issue found in this add-on (cf. https://github.com/nvaccess/addonFiles/pull/310#issuecomment-1100749643).
Converting in draft for now until it is resolved.

**Comment by nvdaes** [comment]
I've removed my request for Reef to review this add-on from now.

**Comment by CyrilleB79** [comment]
@nvdaes: new version released (V2.0-dev-20220417) with initial description updated and new link in get.php.
You can review it again. Thanks.

**Review by nvdaes — APPROVED** [review]
Thanks @CyrilleB79 . I'm approving this.

**Comment by CyrilleB79** [comment]
Since no new issue has been found last week, I have updated to stable release.
@nvdaes you may want to review it again.

**Review by nvdaes — APPROVED** [review]
Thanks @CyrilleB79. I'm approving this after reviewing again.

**Comment by nvdaes** [comment]
@CyrilleB79, though I've approved this, I suggest you to edit release information to reflect that version is 2.0 (stable) for both links (winmag and winmag-dev).

**Comment by nvdaes** [comment]
@feerrenrut , I think this is ready to merge. Please review and proceed when you can.

**Pull request merged**
