### PR TITLE
Update eMule to 4.3

### PR DESCRIPTION
**Pull request by nvdaes**
- [Release page with changes](https://github.com/nvdaes/emule/releases/tag/4.3) (just l10n updates)
- SHA-256 of eMule-4.3.nvda-addon: 3b685cdc31f762de41eb9b4ebc3351fb25173e7f53c7af7d2a327435f706fe0b

### CODE REVIEW

**Review by feerrenrut — APPROVED** [review]
Thanks @nvdaes

**Comment by feerrenrut** [comment]
Oh, this has merge conflicts now, could you please address this?

**Comment by nvdaes** [comment]
I wil look at this ASAP. Thanks.

**Comment by feerrenrut** [comment]
Please merge nvaccess:master into your branch, the diff for this PR is showing lots of changes.

**Review by feerrenrut — APPROVED** [review]
Thanks @nvdaes

**Comment by nvdaes** [comment]
@feerrenrut, merged now.

**Pull request merged**
