### PR TITLE
Update emoticons to 13.4

### PR DESCRIPTION
**Pull request by nvdaes**
## Manifest
- name = emoticons
- summary = Emoticons
- description = Enables the announcement of emoticon names instead of the character Representation.
- author = Chris Leo, Noelia Ruiz Martínez, Mesar Hameed, Francisco Javier Estrada Martínez
url = https://addons.nvda-project.org/addons/emoticons
version = 13.4
docFileName = readme.html
minimumNVDAVersion = 2019.3
lastTestedNVDAVersion = 2020.4
updateChannel = None

## Changes for 13.4
- Updated translations.
- Updated email address of author Mesar Hameed
- sha256 (shown in release page): 860624e237c9ea1360bf27dedd3c8344e3017a4297050869ee9345eeaf160529 emoticons-13.4.nvda-addon
- [Repo](https://github.com/nvdaes/github/emoticons)
- [Release page](https://github.com/nvdaes/emoticons/releases/tag/13.4)

cc: @christianlm (main author)

### CODE REVIEW

**Comment by nvdaes** [comment]
Also cc: @josephsl

**Review by josephsl — APPROVED** [review]
I think the repo was meant to be nvdaes/emoticons - it's okay, I found it. Reef, May I request a second look?

**Comment by nvdaes** [comment]
Sorry for the mistake in the repo. In fact it's
nvdaes/emoticons

Thanks.

**Comment by josephsl** [comment]
Hi, don’t worry.

**Review by feerrenrut — APPROVED** [review]
Thanks @nvdaes and @josephsl 

- [x] URLS are valid
- [x] Manifests are valid
- [x] Quick look at diff against 13.3 looks fine: https://github.com/nvdaes/emoticons/compare/13.3...13.4

**Pull request merged**
