### PR TITLE
add 'mathcat' to the list

### PR DESCRIPTION
**Pull request by NSoiffer**
### Release information
- Name (Example, Add-on Updater):  MathCAT
- Author (example, Your Name): Neil Soiffer
- Repo (example, https://github.com/yourname/addonName):  https://github.com/NSoiffer/MathCATForPython
- Version (example, 21.07): 0.1.14
- Update channel (example, stable, dev or stable and dev): stable
- NVDA compatibility (example, 2021.1 and beyond): 2018.1 and beyond

### Additional information
MathCAT is designed to eventually replace MathPlayer because MathPlayer is no longer supported. MathCAT generates speech and braille from MathML. The speech is enhanced with prosody so that it sounds more natural. The speech can be navigated in three modes using the same commands as MathPlayer. In addition, the navigation node is indicated on a braille display. Both Nemeth and UEB technical are supported.

MathCAT adds a settings menu to NVDA's preferences menu. In the settings menu, numerous options in MathCAT can be set to control the speech, navigation, and braille.

### CODE REVIEW

**Comment by NSoiffer** [comment]
I wasn't clear on whether the compatibility date on this form was the latest version tested or the earliest. I did test on 2018.1 and I suspect it works on earlier versions, but figuring out the true earliest version it works on seems like a case of diminishing returns. I have updated the PR comment to say "2018.1 and beyond".

**Comment by XLTechie** [comment]
Shouldn't this have a key like "mathcat-dev", since it is a dev release? With 
the stable release getting "mathcat"?

Or are you planning to evolve this into a stable release and then stop releasing 
dev versions?

I don't know that we have a requirement of this, but it does seem common in 
the get.php file for dev versions to have a something-dev key.
@nvdaes your thoughts?

**Comment by nvdaes** [comment]
Hello: We don"t have requirements for this regarding reviews. This is something to be decided by authors.

Enviado desde mi iPhone

**Comment by NSoiffer** [comment]
This is a stable release. I've had a number of testers give feedback for a couple of months.

**Comment by XLTechie** [comment]
> More importantly, you have it marked as dev channel in the manifest.

I'm sorry about that, disregard that comment, it is incorrect.

**Comment by NSoiffer** [comment]
I missed that it was still set to 'dev' in buildvar.py. Several sloppy mistakes 8-|. I've updated the addon with the fix ('dev' -> 'None') and built a new release to replace the one at https://github.com/NSoiffer/MathCATForPython/releases/download/v.0.1.14/MathCAT-0.1.14.nvda-addon.

I hope that's the last dumb mistake.

As for the version numbering, the 0.xxx is because I don't feel confident about the underlying APIs that MathCAT exposes for Python. For NVDA, that's really not an issue since there isn't an exposed Python API because the python code is included in the add-on. So there is a good case I should separate out the NVDA add-on numbering from the underlying Rust code numbering. The only API that the MathCAT NVDA addon sort of exposes are the user settings. Those are likely to change as more features are added and I get more user requests, so there is still a case that a leading '0' for the version number is reasonable.

If someone feels strongly about this, I'll change the version number.

**Comment by XLTechie** [comment]
> More importantly, you have it marked as dev channel in the manifest.

Specifically, I believe the tool I was using to pull manifests pulled an older 
one, probably because of an URL error on my part, or a diff error of some kind. 
I have already updated the procedure, but am still investigating why I got
  a manifest with dev listed.

Apologies. Now added to Add-on Updater.

**Comment by XLTechie** [comment]
> I've updated the addon with the fix ('dev' -> 'None') and built a new release to replace the one at https://github.com/NSoiffer/MathCATForPython/releases/download/v.0.1.14/MathCAT-0.1.14.nvda-addon.

Ah. That explains why my add-on grabber found dev this morning, and None now, 
for the same version package. I thought I was losing it. :)

**Pull request merged**
