### PR TITLE
Rename debugHelper to devHelper, and make 2021.1 compatible.

### PR DESCRIPTION
**Pull request by XLTechie**
Confirmed and configured for 2021.1 compatibility; no code changes necessary.

Renamed from debugHelper to devHelper.
Pushing name change quickly without changing get.php key, per advice from @josephsl, to make the name change work smoothly with Add-on Updater.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, a corresponding Add-on Updater (coming July) will start checking for Dev Helper. Alternatively, there is a temporary solution proposal that will make it easier for Add-on Updater users without having to release an add-on version just to edit add-on update keys. Thanks.

**Comment by nvdaes** [comment]
Hi, Luke and Joseph. For coordination, I assume that Joseph will review this PR since he commented before than me.

Anyway, I'll mention this add-on as compatible (coming soon) in the nvdacompat add-ons document, as done when pull request against add-on files are opened, requesting update an add-on on the website.

Cheers

**Review by josephsl — APPROVED** [review]
Add-on Update notes: both the add-on and the JSON file (see Add-ons List discussion for details on a proposal about this) will be edited.

**Comment by XLTechie** [comment]
Thanks Joseph.
In what way does the add-on need to be edited?

**Comment by josephsl** [comment]
Hi, adding an alias of Debug Helper to a mapping of add-on identifiers to update keys (“devHelper”: “whatEverTheExistingKeyIs’). Thanks.

**Pull request merged**
