### PR TITLE
Windows App Essentials 22.06/22.06.1

### PR DESCRIPTION
**Pull request by josephsl**
### Release information
- Name: Windows App Essentials
- Author: Joseph Lee, Derek Riemer and contributors
- Repo: https://github.com/josephsl/wintenapps
- Version: 22.06/22.06.1
- Update channel: stable
- NVDA compatibility: 2021.3 and later
- Sha256: 68f2dfd85798fd49480cce2d9efd47a3e2a103adcdb1f3bccd8656b4a3e3a417

### Changelog (mention changes in separate lines starting with dash space)
- Added support for Voice access (Windows 11 Version 22H2 preview).
- Initial support for Suggested Actions presented by modern keyboard (Windows 11 Insider Preview).
- Modern keyboard: in Insider Preview build 25115, NVDA will announce suggested actions when compatible data such as phone numbers is copied to the clipboard.
- Notepad (Windows 11): Removed text repetition fix as it is resolved in Notepad 11.2203.
- Notepad (Windows 11): Fixed a regression introduced in add-on 22.05 where NVDA did nothing or played error tones when trying to read status bar text.
- Voice access: NVDA will announce microphone toggle status when pressing Space or Enter keys while focused on microphone button.

### Additional information
Version 22.06.1 resolves Start button announcement issue reported by a user, otherwise identical to 22.06.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Showstopper: nvaccess/nvda#13717, please do not approve until the mentioned issue is resolved.

Thanks.

**Review by nvdaes — APPROVED** [review]

**Comment by josephsl** [comment]
Hi, actually, no –there is an outstanding issue that’s being investigated that can actually cause the hash to change if a fix is implemented. One workaround is releasing 22.06.1 as a follow-up, something I’m willing to do in a new PR. Thanks.

**Comment by josephsl** [comment]
Hi all,

Although 22.06 was approved, a major issue was found by a Brazilian user who noted that NVDA does not announce Start button in Windows 11 (turns out on this particular system, Windows 11 Start button is seen as IAccessible rather than UIA). As this is a major issue, I'll post 22.06.1 (same branch); my apoogies for getting you to approve a newer version of this when it was already approved.

Thanks.

**Review by nvdaes — APPROVED** [review]

**Comment by josephsl** [comment]
Hi, thanks for approving – again my apologies for this mess. Thanks.

**Pull request merged**
