### PR TITLE
Add Speech History v2022.1

### PR DESCRIPTION
**Pull request by jscholes**
### Release information
- Name: Speech History
- Author: James Scholes
- Repo: https://github.com/jscholes/nvda-speech-history
- Version: 2022.1
- Update channel: stable
- NVDA compatibility: 2019.3 to 2022.1

### Changelog (mention changes in separate lines starting with dash space)
- Compatibility with NVDA version 2022.1

### CODE REVIEW

**Review by josephsl — COMMENTED** [review]
Could you mind specifying the add-on version in the file name please? Thanks.

**Comment by jscholes** [comment]
@josephsl Done.  I had already shared the URL publically, so I uploaded a copy of the add-on with a different filename.

Please note that neither the README in this repo, nor the [Requirements for add-on submissions](https://addons.nvda-project.org/requirements.en.html) page mention such a requirement.  I suggest that either:

1. filenaming requirements be documented; or
2. filenaming requirements be enforced server-side at download time; or
3. there be no filenaming requirements.

**Review by josephsl — APPROVED** [review]
Thanks so much (and sorry for all those anxious messages on the add-ons list, at least I'm feeling a bit better now).

**Comment by josephsl** [comment]
Hi, I think the first option would be the best way for us as it allows users to also identify releases easily (thanks for a reminder on that). Thanks.

**Pull request merged**
