### PR TITLE
Training Keyboard Commands 2.4 (initial, author: Ibrahim Hamadeh)

### PR DESCRIPTION
**Pull request by josephsl**
## Introduction:

"""This addon allows you to train NVDA commands in game like way, for either desktop or laptop layout mode.
For every commands and it's description, you have to choose the right keys or answer specific to it.
And if exiting before the end, you can save the remaining questions to resume them in later time.
In order to use the addon, you have to assign a gesture to it via NVDAmenu>preferences>inputGestures>trainingKeyboardCommands.

## Release information:

* Name: Training Keyboard Commands
* Author: Ibrahim Hamadeh
* Repo: https://github.com/ibrahim-s/trainingNvdaCommands
* Version: 2.4
* Update channel: stable
* NVDA compatibility: 2019.3 to 2021.1
* Sha256: e67c65472aff37854f957912daf2f9da18ef5c7c342be54ea892b006511da5b5

Thanks.

### CODE REVIEW

**Review by nvdaes — COMMENTED** [review]
Hello @ibrahim-s 
In the readme.html file, the add-on claims to be compatible 2019.3 to 2019.4.

I think it's preferrable to remove this from documentation or reflect that it's compatible with NVDA 2019.3 and beyond.

I won't approve this PR for now, in case you want to review the documentation.

**Comment by ibrahim-s** [comment]
Hello
yes it was a bug in readme and I have fixed it
if there are actions more I have to do please tell me
regards

**Comment by ibrahim-s** [comment]
sorry
well yes I have realized that the readme in the builded addon is not fixed
so yes give me a sometime to fix it
thank you

**Comment by ibrahim-s** [comment]
Hello
well now I think all is fixed
readme on github and readme.html in the binary
reflect the same compatibility, 2019.3 to 2021.1
if something else please tell me
regards

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Hello, I have approved this PR.


Note: you have reflected compatibility until 2021.1, but you may prefer to write compatibility: 2019.3 and beyond, like done by other authors, since the add-on will be compatible with future version and maybe easier to maintain.
Anyway this can be done when you release a maintenance version. I think that this can be merged like that.
Thanks

**Comment by ibrahim-s** [comment]
OK,
I will do that in future releases, thanks a lot.
regards

**Pull request merged**
