### PR TITLE
Registering addon Search With version 1.2

### PR DESCRIPTION
**Pull request by ibrahim-s**
### Release information
- Name : Search With
- Author  : Ibrahim Hamadeh
- Repo : https://github.com/ibrahim-s/searchWith
- Version : 1.2
- Update channel : stable
- NVDA compatibility : 2019.3 and beyond
- Add-on repo update key: searchwith
### Additional information
This addon helps you to search text, via various search engines.
Let no text selected, and press the gesture of the addon
A dialog will be displayed, with an edit box to enter a search query
To search with Google press enter, or tab to search with other engins.
Or
select some text and press once, a menu will be displayed with various search engines to choose.
And while text is selected, you can press the gesture twice to search with Google directly.

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]
- Reviewed in this [thread on the add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/message/16339)


@ibrahim-s, I read that you want this add-on to be registered in the translation system. Please, create a stable branch in your repo and let us know so that we can fork it in nvdaaddons organization, as described at

https://github.com/nvaccess/mrconfig


Also, let us know if you need assistance to include the add-on documentation on the website (the svn repo) when this PR is merged.

**Comment by ibrahim-s** [comment]
Thank you for approving my request
I have made a stable branch in the repo
and hope I go for including it in the translation system
As for now really I am not a member of the translation system
and do not know how to include the documentation page on the website or in SVN repo
don't know what you suggest in this case
I will be happy to hear your suggestion
kind regards.

**Comment by nvdaes** [comment]
Hello. You can request an invitation in the translations mailing list and follow the process seeing documentation created by other add-ons, or, if you prefer, I'll create it for you this time.

The process is documented at

https://github.com/nvaccess/nvda/wiki/TranslatingUsingAutomaticProcess

I'll create an issue in the mrconfig repo so it's registered in the translations system.

**Comment by ibrahim-s** [comment]
Hello,
Well, I prefer if you don't mind, to create it yourself this time  only.
and I will request an invitation from the translation list, hoping to understand this system more.
appreciate your efforts.
thank you

**Comment by nvdaes** [comment]
OK, I'll continue tomorrow work about NVDA and add-ons. So, if you haven't received an invitation then, I'll send it to you. And this time I'll update the documentation.

Note: I may improve the format (not too much), just to be consistent with the website.
Kind regards

**Comment by ibrahim-s** [comment]
Hi,
Yes, I have received an invitation and accepted it.
Thanks a lot
and about the format, no problem
best regards

**Comment by ibrahim-s** [comment]
Hello Noelia
Then it is the file addonName.mdwn, that should be added in svn repo
If you have not added it yet, then let me try to add it myself
I think it should be added after the addon is registered, and PR merged, right?
appreciate your work
thank you

**Comment by nvdaes** [comment]
Hello, excelent!
You can add addonName.mdwn to svn when this pr is merged. Then the add-on will be registered in the translations system so it can receive .md files in the addon/doc folder, in different subfolders for each language like en, ar, etc, generated from translations made in svn for the website, and .po files in the locale folder. So, you should add the .mdwn file to svn when this PR is merged. After that it can be registered in mrconfig. I requested it in the corresponding issue and gave you access to the repo where translations will be send, so you can send changes to stable branch for example when new translatable messages are available.
You can see documentation about this in nvaccess/mrconfig repo. And for me GitHub actions are very useful to receive translations automatically in my add-on repos from nvdaaddons organization. Feel free to use my .yaml files if they fit your needs.
In the .mdwn file, use a title for the first heading level one, and the download link based on get.php like done in other add-ons, so ikiwiki processes the link properly avoiding UrL too long; also in this way you can use a permanent URL for different versions. You may include it also in your readme.md.
Don't forget to include dev stable tags, which make the documentation available in the stable and dev sections of the website.
Also, try to use a consistent format avoiding dashes for lists. Use asterisks instead since dashes are GitHub flavored markdown and seem not to be supported by Ikiwiki. I have seen an extra carriage return after the word or, I think, in the readme. I advice you to take care of the format making readable paragraphs and using heading levels to structure the document.
Kind regards

**Comment by ibrahim-s** [comment]
OK Noelia,
I will make my best to follow your instructions
thanks for this explanation and help
best regards

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
