### PR TITLE
Added Newfon speech synthesizer

### PR DESCRIPTION
**Pull request by DraganRatkovich**
### Release information
- Name: Newfon
- Author: Sergey Shishmintsev, Alexy Sadovoi, Sergey A.K.A. Electrik, Kvark and other developers
- Repo: https://github.com/DraganRatkovich/newfon
- Version: 2022.04.16
- Update channel: stable
- NVDA compatibility: from 2019.2 to 2022.2

### Additional information

All information, as well as the changelog, is published in the repository's readme file.

### CODE REVIEW

**Comment by DraganRatkovich** [comment]
@feerrenrut Newfon is on the NVDA addon site, although it hasn't been updated for a long time, so I decided to fix this situation. The authors are aware of this and have given permission to update the release. Also, please make it possible to translate the website section of this add-on via the SVN repository. Later I will also write to the translator mailing list to be able to translate the synthesizer interface via SVN.

**Review by nvdaes — CHANGES_REQUESTED** [review]
Hello: I'm one of the reviewers of this repo with Joseph Lee, and we have to approve pull requests before Reef look at them. I'd like to suggest that newfone is placed under nb. Can you do it? Generally ids of add-ons are in alphabetical order. Thanks.

**Review by DraganRatkovich — COMMENTED** [review]
@nvdaes Thanks for the feedback, I've changed the order of the link.

**Review by nvdaes — APPROVED** [review]

**Comment by jmdaweb** [comment]
Hi,
Please note: this release has been deleted and re-created at least twice after opening the pull request. I have received two e-mail notifications with new releases and same version number.

**Comment by DraganRatkovich** [comment]
Hello,
@jmdaweb Yes, I know that, but it doesn't affect the link in the get.php file because the tag and the link are the same. I just fixed a few minor issues

**Comment by josephsl** [comment]
Hi, while Noelia has already approved this particular PR, if I’m asked to review this after learning that the version submitted for distribution is different than what users will actually get in terms of content, then I’d ask folks to reconsider. There are three options: distribute the submitted version despite changes to content, change the version text, or if implemented later, submit an updated hash value; of these, the first option seems to be the most practical for this repository, although in the ideal case the second option would be better. As I noted above, I’ll leave it up to add-on maintainers to decide as the authority over add-on releases falls on authors. Thanks.

**Comment by DraganRatkovich** [comment]
Hi,
@josephsl There is no change to the version number or content of the add-on, I just made it to match the format of the NVDA add-on website. More precisely, I added some missing headers to the Python files. When I first submitted the PR, I unfortunately forgot to add the headers mentioned, so I removed the release, fixed the missing Python headers, and recreated the release, but the tag, as well as the direct download link, remained the same as they were in the get.php file.

**Comment by josephsl** [comment]
Hi, in this case, I think it would be best to give this PR an exceptionl in the future though, please do tell us changes if any so folks will not be confused. As for reviewing this PR, I’ll leave it up to Noelia as she reviewed it for you before. Thanks.

**Comment by DraganRatkovich** [comment]
@josephsl Of course, if anything new comes up that could affect the content or version number of the add-on, I'll update the release information in the PR. As for the merge, it's entirely up to maintainers of repo. If there are no problems, then you can merge.

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Hello:

I approved these changes before after each commit.
@DraganRatkovich : I suppose you've requested my review accidentally. So I won't review this again.

**Comment by jmdaweb** [comment]
Hi,
A new release was recreated on july 8 at 15:43 UTC. I imagine it contains the mentioned change on readme.

**Comment by DraganRatkovich** [comment]
Hello,
@nvdaes, @jmdaweb is right. I've added a new commit that needs approval, so please review it.

**Comment by nvdaes** [comment]
I have seen 2 commits to addonFiles repo, and I reviewed them. In case you make changes to the manifest.ini file in the provided link, then let me know to review changes. Anyway, be aware that, once approved, your pull request can be merged at any moment, so it"s beter to send the PR when you are sure about what you want to send.

Enviado desde mi iPhone

**Comment by DraganRatkovich** [comment]
@nvdaes I understand, thanks.

**Comment by nvdaes** [comment]
I"ll review this once again, but please consider create inmutable releases so that name and version serves to identify binaries. Also,you can look at the addon-datastore repo by NV Access, and you"ll see that SHA-256 may be used to ensure that binaries are not changed.

**Review by nvdaes — APPROVED** [review]

**Comment by XLTechie** [comment]
Entry added to add-ons metadata.

**Comment by josephsl** [comment]
Hi, I’ll leave it up to new add-on maintainers to decide, but my general opinion is that this PR should be reconsidered if it turns out the new releases warrant changing version text reported to users. I’m sure there are reasons to keep the version number the same, but it will raise serious questions in the future when NV Access add-ons datastore is ready to accept submissions from the community, specifically in light of optional SHA256 checks in the future (even if the version text remains the same, SHA values will not match); even if an add-on release that merely reverts changes is introduced, users will notice hash mismatches for a time period. Thanks.

**Comment by seanbudd** [comment]
@josephsl - what do you mean by reconsidered? this add-on has been merged to the Add-on website already

**Pull request merged**
