### PR TITLE
Updating Tony's addons versions

### PR DESCRIPTION
**Pull request by mltony**
I updated my add-ons to be compatible with NVDA v2021. Updating download links.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi, can you provide release info for each add-on please? Thanks.

**Comment by mltony** [comment]
Here you go:
# AudioChart v1.3
- Compatibility with NVDA v2021.1
# Bluetooth Audio v1.3
- Compatibility with NVDA v2021.1
# BrowserNav v1.14
- Added a feature to skip empty lines/paragraphs, and lines/paragraphs matching skip regex
- Go back to previous cursor location on the page    
- Compatibility with NVDA v2021.1
- Bugfixes
# Console Toolkit v1.1
- Compatibility with NVDA v2021.1
- Better compatibility with Putty terminal
# IndentNav v1.12
- Compatibility with NVDA v2021.1
- Added feature to select multiple indented blocks when pressing NVDA+Control+I repeatedly.
- Added indent-paste keystroke bound to NVDA+V
# Phonetic punctuation v1.3
- Compatibility with NVDA v2021.1
- Adding prosody audio rules
- New contributed earcon for backslash character
# SentenceNav 2.11
- Compatibility with NVDA v2021.1
# TexNav v1.5
- Compatibility with NVDA v2021.1
#Tony's enhancements v1.10
- Compatibility with NVDA v2021.1
- Added read row/column commands.
- Added commands to show/hide windows.
# WordNav 1.4
- Compatibility with NVDA v2021.1

**Comment by josephsl** [comment]
Hi, I see. @NVDAEs, any thoughts? Thanks.

**Comment by nvdaes** [comment]
You may continue reviewing this if you want, @josephsl.
Cheers

**Comment by josephsl** [comment]
@mltony, can you  try fixing conflicts in get.php based on more recent master branch commits? Once that's done, I'll review these add-ons.

Thanks.

**Comment by mltony** [comment]
@josephsl, I rebased, so now there are no conflicts, but for some reason it says that I want to merge 38 commits - but most of these commits are from master branch. I'm not good at git, so let me know if that's a problem.

**Comment by josephsl** [comment]
Hi, another approach is using a temporary branch to hold whatever info you’ve got on your add-ons, and then creating a new branch for the PR then doing “git merge –no-ff –no-commit tempbranch” on top of the PR branch. Of course the PR branch should be based on latest master branch commit. Once these steps are done, commit changes and do a forced push (git push –force). Or, even better, let’s start a different PR based on latest master branch, and in the new PR branch, commit one add-on change at a time instead of doing all at once – this makes it easier for reviewers to track individual changes. Thanks.

**Review by feerrenrut — CHANGES_REQUESTED** [review]
This changes addon versions other than those listed in the comment, including Josephs addons' it is best to create single PR per updated addon, so that in the event of a mistake on one of them then updating the rest isn't blocked.

While you can certainly correct this, it might be easier to close this PR and start again, modifying a single addon per PR.

**Comment by feerrenrut** [comment]
This seems to be replaced by PR https://github.com/nvaccess/addonFiles/pull/105, thus I'll close this one. Please correct me if I've made a mistake here.

**Comment by mltony** [comment]
Yes,you are correct,  this is replaced by that PR. Sorry, I should've 
closed this old PR myself.

**Pull request closed without merging**
