### PR TITLE
Add ThunderbirdPlus add-on

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Release information
- Name (Example, Add-on Updater): Thunderbird+
- Author (example, Your Name): Pierre-Louis Renaud, Daniel Poiraud
- Repo (example, https://github.com/yourname/addonName): https://github.com/RPTools-org/ThunderbirdPlus
- Version (example, 21.07): 4.5
- Update channel (example, stable, dev or stable and dev): stable
- NVDA compatibility (example, 2021.1 and beyond): 2019.3 to 2023.1

### Changelog (mention changes in separate lines starting with dash space)
First request to include this add-on; see doc/en/changes_en.html for full change log.

### Additional information
* Request done on behalf of Pierre-Louis Renaud (@RPTools-org).
* PR initially made with version 4.4, updated to 4.5 since the previous one was not validated on time.

### CODE REVIEW

**Comment by josephsl** [comment]
Note to reviewers: a discussion took place on an NVDA list about combining this add-on with Mozilla Apps Enhancements, and the author gave reasons for keeping these add-ons separate. Thanks.

**Review by nvdaes — COMMENTED** [review]
I think tbp should be placed before tbx. Any reason for not doing it?

**Comment by CyrilleB79** [comment]
> I think tbp should be placed before tbx. Any reason for not doing it?

Sorry, it's my mistake. I had initially put a longer key (thunderbirdplus) and hhave then shortened it without reordering the key.
I have changed the place of the key now.

**Review by nvdaes — APPROVED** [review]

**Comment by CyrilleB79** [comment]
@seanbudd, @michaelDCurran: You both have recently merged other pull requests in this repo (less than one week ago).

This PR has been approved by Noelia for 3 weeks. Any reason why it has not been merged along with other PRs last week?

Please let us know so that this add-on can be finally published on the community website. Thanks!

**Comment by nvdaes** [comment]
Hi Cyrille, in fact I approved this. Just a reminder: should be this add-on updated to be compatible with NVDA 2023.1 before merging?
Cheers.

**Comment by CyrilleB79** [comment]
Version updated to 4.5 (compatible 2023.1) since NVDA beta has been released meanwhile.

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Hi Cyrille: I've approved this again andI confirm that this is compatible with NVDA 2023.1.

**Comment by nvdaes** [comment]
I've just detected a bad typo: in the aknowledgments word. Seems to be
good though personally for me is more comfortable to use headings
instead of nested lists.
Since you've updated the documentation and it may be translated, as
you know, if you want, you can request to include the add-on in the
translation system as explained in nvaccess/mrconfig repo.

2023-02-20 14:07 GMT+01:00, Cyrille Bougot ***@***.***>:

**Pull request merged**
