### PR TITLE
Added cliptools.

### PR DESCRIPTION
**Pull request by TheQuinbox**
I have added my new NVDA addon, Cliptools to get.php. I would also like to have this addon checked by the community, and put up on the front page of the addons website.
Thank you!

### CODE REVIEW

**Comment by TheQuinbox** [comment]
Lots more info.
## Introduction:
This addon aims to provide many clipboard related functions to NVDA. Currently, it allows you to read the current  clipboard content in a text field, as well as edit it, allowing users to delete unwanted bits of text from their clipboard. A lot more is planned!
## Release information:
• Name: Cliptools
• Author: Quin Marilyn
• Repo: https://github.com/TheQuinbox/cliptools
• Version: 2021.1
• Add-on update channel: stable
• NVDA compatibility: 2021.1 and later. It also works with 2019.3 to 2020.4, but the manifest states 2021.1.0.
• Add-on files update key: cliptools
Thanks.

**Comment by josephsl** [comment]
Hi, I have forwarded your request to add-ons list, but first, we need to know what this add-on is and repository so folks can find it easily. Thanks.

**Comment by josephsl** [comment]
Hi, in this case, ignore my earlier message. I advise talking to @NVDAES who maintains Clip Contents Designer and see how compatible both add-ons are. Thanks.

**Comment by TheQuinbox** [comment]
Oh, there's an addon that serves a similar purpose? Sorry, I wasn't aware.


OK, looking at it, it does seem similar, at least to this version. I do plan to add more however, so I'm not sure if merging the two would necessarily work. Thanks for forwarding it to the list, by the way. :).

**Comment by josephsl** [comment]
Hi,

Basic review results (based on 2021.1 and latest master branch commit from the repo):

* License and copyright: pass
* Documentation: pass (note that add-on readme will not be shown to users from Add-ons Manager dialog, but for this one, it's understandable since you are starting out)
* User experience: pass (I do know that you have new commits which notes that messages are not translatable at this time)
* Security: pass if the add-on will not be used in secure screens (if it is, I recommend putting globalVars.appArgs.secure flag check)

Comments:

* Add-on name should start with lowercase, as the name flag in the manifest is the internal identifier. It doesn't affect add-on summary.
* Normally the add-on is listed under development section, but since you labeled it as stable, we'll label it as "stable" on community add-ons website once approved for distribution.
* The add-on source code is simple and elegant.

I recommend a green light (ready for distribution); I'll wait for Noelia's comments before officially approving it.

Thanks.

**Comment by TheQuinbox** [comment]
Awesome, thanks. I'll fix the capital. :)

**Review by nvdaes — COMMENTED** [review]
Hello @TheQuinbox , thanks for joining the add-ons community and share your work with us.

This is Noelia, first author of an add-on renamed to clipContentsDesigner as suggested by a member of the community, contributed by several members and translated into different languages.

For this reason I'm maintaining it and I haven't reviewed your source code (I'll ensure it's compatible with NVDA 2021.1), and since the add-ons may have similar functionality, I may loose the focus. ☺

Anyway, I've installed your add-on and, from my personal point of view testing right now, user experience should be improved before posting it on the website:

1. Copy some text to the clipboard
2. Press NVDA+e, shown in miscellaneous category of input gestures) 
3. Copy some folder to the clipboard
4. Press NVDA+e and press OK in the add-on dialog

To close this dialog, I have to open the NVDA's log or restart NVDA.

```
ERROR - scriptHandler.executeScript (06:16:41.812) - MainThread (7472):
error executing script: <bound method GlobalPlugin.script_editClipboardText of <globalPlugins.cliptools.GlobalPlugin object at 0x0718C9D0>> with gesture 'NVDA+e'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "C:\Users\User\AppData\Roaming\nvda\addons\Cliptools\globalPlugins\cliptools.py", line 60, in script_editClipboardText
    d = ClipDialog()
  File "C:\Users\User\AppData\Roaming\nvda\addons\Cliptools\globalPlugins\cliptools.py", line 40, in __init__
    self.edit.SetValue(api.getClipData())
  File "api.pyc", line 338, in getClipData
  File "winUser.pyc", line 784, in getClipboardData
OSError: [WinError 0] La operación se completó correctamente.
``` 

Have a nice day!

**Comment by TheQuinbox** [comment]
Hello.
I actually fixed this error in a later commit, but it wasn't in the release. Should I push a 2021.1.1?

**Comment by josephsl** [comment]
Hi, normally the answer is “yes”, but since this is a new add-on, I don’t think you have to create a new release just for this at this time. Thanks.

**Comment by feerrenrut** [comment]
@TheQuinbox Please let us know when this is done so @nvdaes can complete the review.

**Comment by nvdaes** [comment]
Yes please. Modify get.php and provide a link to a .nvda-addon binary which fixes the mentioned bug, and I"ll review it again. Thanks.

**Comment by TheQuinbox** [comment]
Whoa, sorry, this completely slipped my mind, so 2021.1 is now uploaded, with those fixes, as well as some things, such as translations, although I'm not sure if I did it right. Also updated get.php. Let me know how it looks! :)

**Comment by nvdaes** [comment]
Hello, thanks for taking care about this. I'll review this when I can.
To list add-ons on the website, for now a review should be requested on the add-ons mailing list so more people can provide feedback. There are pending add-ons sent to the list for review, so I'll prioritize them.
Please see

https://addons.nvda-project.org/index.en.html

Cheers

**Review by nvdaes — COMMENTED** [review]
Hello @TheQuinbox , thanks again for sharing your work with the community.
This will be my last comment on this PR until a new review process is set, maybe when the new add-on store is in place. The reason is that I'll focus my attention on reviewing add-ons sent to the mailing list, as mentioned on the website.
Anyway these are my comments:

- The mentioned bug is fixed.
- The feature to show the clipboard text, for me, at least sometimes presents symbols, not the text with appropriate codification.
- The command to clear the clipboard contents clears just the text, but if I copy a file I can paste it. But the message presented says that clipboard is empty.
- This command is assigned to keystrokes used by NVDA itself for some applications, and the add-on would prevent to use NVDA as expected unless keystrokes are reasigned.

You may find useful to request feedback on the add-ons mailing list. If you're interested, feel free to subscribe.
Kind regards

**Comment by TheQuinbox** [comment]
AFAIK, this addon is now on the new host, so closing this.

**Pull request closed without merging**
