### PR TITLE
Update Character Information

### PR DESCRIPTION
**Pull request by CyrilleB79**
### Release information
- Name (Example, Add-on Updater): Character Information
- Author (example, Your Name): Cyrille Bougot
- Repo (example, https://github.com/yourname/addonName): https://github.com/CyrilleB79/charInfo
- Version: V1.8-dev-20220416
- Update channel (example, stable, dev or stable and dev): dev
- NVDA compatibility (example, 2021.1 and beyond): 2019.3 and beyond

### Changelog (mention changes in separate lines starting with dash space)

- Update to Unicode 14.0.
- Compatibility with NVDA 2022.1.
- Drops compatibility with NVDA below 2019.3.
- The release is now performed thanks to a GitHub action instead of appVeyor.
- Update localizations.

### Additional information

PR initially opened for V1.8-dev-20220415 and updated for V1.8-dev-20220416.

### CODE REVIEW

**Comment by nvdaes** [comment]
@Feerrenrut, I approve this. Please review and merge when you can. Seems GitHub interface has changed or something and I cannot review this properly.

**Review by nvdaes — APPROVED** [review]
I'm approving this properly. Previously, the problem was that my window was not maximized and then the Review button was not presented.
@CyrilleB79 , I've reviewed this opening the add-on with 7zip and I don't see the doc/en/readme.html file. Is this expected? This doesn't affect this approval, and the same is true for winmag.

**Comment by CyrilleB79** [comment]
> @CyrilleB79 , I've reviewed this opening the add-on with 7zip and I don't see the doc/en/readme.html file. Is this expected? This doesn't affect this approval, and the same is true for winmag.

Good catch! No it was not intended at all. Converting this PR to draft until I have solved this issue.
It seems that it is due to a case issue on the `readme.md` file. It appears only now since the release is now performed with GitHub action on a virtual Linux machine whereas I previously did the releases with appVeyor on a virtual Windows machine.

**Comment by CyrilleB79** [comment]
@nvdaes I am re-requesting review since I have updated the version in the initial description and the link in get.php. Thanks.

**Review by nvdaes — APPROVED** [review]

**Comment by CyrilleB79** [comment]
Since no new issue has been found last week, I have updated to stable release.
@nvdaes you may want to review it again.

**Review by nvdaes — APPROVED** [review]
@CyrilleB79 , I'm approving this update. You may to update your initial comment on this PR (optionally), and for the next version, you may set an URL in manifest.ini, for example your repo to send issues or pull requests there. Thanks

**Comment by nvdaes** [comment]
@feerrenrut, I dont know how to re-request your review. This is ready to merge. Thanks.

**Pull request merged**
