### PR TITLE
Enhanced Phonetic Reading 1.1.3 (David ACM)

### PR DESCRIPTION
**Pull request by josephsl**
### Release information
- Name: Enhanced Phonetic Reading
- Author: David CM
- Repo: https://github.com/davidacm/EnhancedPhoneticReading
- Version: 1.1.2-dev
- Update channel: dev
- NVDA compatibility: 2018.3 and later

### Changelog (mention changes in separate lines starting with dash space)
- Updated manifest to add compatibility with NVDA 2022.1.1.
- now core.callLater is used instead of python threads. This solves issues with another add-ons like bluetooth-audio.
- internal code changes.

### Additional information
Submitting on behalf of @davidacm

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

IMPORTANT: update channel is actually shown as "stable" in add-on manifest despite the version being a dev build.

**Review by nvdaes — CHANGES_REQUESTED** [review]
Hello:

The last tested version is set to 2022.1.1, which doesn't exist, so I won't approve this for now.

**Comment by josephsl** [comment]
Hi,

@davidacm, any comments?

**Comment by CyrilleB79** [comment]
Ping @davidacm 

Probably a very minor error is preventing this add-on from being integrated on the website.

**Comment by josephsl** [comment]
Hi,

Any updates now that what I think is the core idea behind this add-on is integrated into NVDA Core?

Thanks.

**Comment by davidacm** [comment]
Hi @josephsl.
I don't know if you read the conversation in the
[13550 pr of NVDA](https://github.com/nvaccess/nvda/pull/13550)...
But this add-on is using a different method for the delayed character descriptions compared with the core implementation.
Core implementation, at least the last time I checked it, is using breakCommand pauses. Although it can look as a good idea, in fact is problematic for many users, who told me about their concerns both in the pr comments and privately.
That's is because most of synthesizers, are inaccurate in the pauses made with the break command.
Most of them change the pause time according to the configured speed rate. The higher the speed, the shorter the pause. It can be very noticeable on sapi5 and one core synthesizers. But even in Espeak you can notice this drawback although it's less noticeable than in other synths.

In fact, some synths don't support breakCommand at all.
Even if NVDA fix it on the core synthesizers, tey can't control the implementation  in third-party synths.
I am thinking, for example, in international languages, where there are many sitetizers over which nobody has control, or probably are not known to us.
Even if they are not official, we must have consideration for the users who do use them.

That said, I will have to continue supporting this add-on, because the core feature is problematic even for me as I am a user who changes the speed of the synthesizers very often; it depends on the environment conditions or the activity I'm doing in a specific time.

If you want to know more information about this, you can read the comments in the linked pr above.

Regards,
David.

**Comment by davidacm** [comment]
P.S. I did not reply to comments here earlier because I was too busy and because I was working on the core implementation of this add-on. But due to the issues mentioned in my previous comment some users soggested me to continue supporting this, and I agree with them.

**Comment by josephsl** [comment]
Hi, I did read the comments on that PR. Would you like folks to review what we have (this PR) or would like to create a new PR addressing review comments raised? Thanks.

**Comment by davidacm** [comment]
Hi. I think that is not necessary to open another pr. I updated the get.php file, and I deleted the dev version because no issues were reported in some months.

**Comment by davidacm** [comment]
this is the link for the new release. I thought that I created a pr, but I guess I forgot to send the pr here.

https://github.com/davidacm/EnhancedPhoneticReading/releases/download/1.1.3/EnhancedPhoneticReading-1.1.3.nvda-addon

**Comment by josephsl** [comment]
Hi,

In this case, I'll restructure this pull request i.e. rename it. The branch will be kept for convenience.

Thanks.

**Review by nvdaes — APPROVED** [review]
Note that the add-on name starts with e capital character. This is right, but it must be considered if the add-on is registered for translations, trying that the repo forked in nvdaaddons organization is also named starting with a capitalized E. I think that issues have arised in the past due to this.

**Pull request merged**
