### PR TITLE
MSEdgeDiscardAnnouncements-v0.5 release

### PR DESCRIPTION
**Pull request by beqabeqa473**
### Release information
- Name (Example, Add-on Updater): MSEdgeDiscardAnnouncements
- Author (example, Your Name): "Beqa Gozalishvili <beqaprogger@gmail.com>""
- Repo (example, https://github.com/yourname/addonName): https://github.com/beqabeqa473/MSEdgeDiscardAnnouncements
- Version (example, 21.07): 0.5
- Update channel (example, stable, dev or stable and dev): Stable
- NVDA compatibility (example, 2021.1 and beyond): 2019.3 and beyond

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Do you plan to add documentation (readme, perhaps) and copyright header for settings module in the later version?

Thanks.

**Comment by beqabeqa473** [comment]
Yes, perhaps i'll use addon-template for the next version and add
translations support.

On 1/5/22, Joseph Lee ***@***.***> wrote:
> Hi,
>
> Do you plan to add documentation (readme, perhaps) and copyright header for
> settings module in the later version?
>
> Thanks.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/addonFiles/pull/250#issuecomment-1005407678
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by josephsl** [comment]
Hi, in this case, I’ll sign this off unless @nvdaes and others have further comments. Thanks for your hard work on this add-on.

**Comment by nvdaes** [comment]
Hello: I don't have comments, just that you want to provide info about the channel, and hope you can add support for translations.
Thanks

**Review by josephsl — APPROVED** [review]
Thanks for your hard work.

**Comment by nvdaes** [comment]
@josephsl, I think you made a mistake and requested my review instead of @feerrenrut

**Comment by josephsl** [comment]
Hi,

You're right...

**Comment by beqabeqa473** [comment]
Hi.

Ok, i've added documentation and translations support in 0.5 release.
Should i update PR?

On 1/5/22, Joseph Lee ***@***.***> wrote:
> Hi,
>
> You're right...
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/addonFiles/pull/250#issuecomment-1005430307
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by josephsl** [comment]
Hi, I don’t think so. I’ll approve this one also.

**Review by josephsl — APPROVED** [review]

**Pull request merged**
