### PR TITLE
Remove Bit Che

### PR DESCRIPTION
**Pull request by ABuffEr**
Hi,

my first pr here.

I edited get.php removing keys for Bit Che, declared as unsupported on own repo:

https://github.com/ABuffEr/bitChe

The archived add-on repo keeps also a copy of bitChe-2.8.nvda-addon hosted here, so you can delete it, if you want.

Cheers.

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]

**Comment by lukaszgo1** [comment]
> The archived add-on repo keeps also a copy of bitChe-2.8.nvda-addon hosted here, so you can delete it, if you want.

Any particular reason not to do so as part of this PR?

**Comment by ABuffEr** [comment]
> Any particular reason not to do so as part of this PR?

I read some time ago about historical reasons in managing this repo, so I was not sure what to do (but no problem on my side about this specific deletion).

**Comment by nvdaes** [comment]
You may wait for @feerrenrut review to see if the binary should remain or not.

**Comment by nvdaes** [comment]
Hi Alberto, I've moved the documentation of bitChe to the legacy section of the website. This PR is similar (not exactly) to PR #6 

@feerrenrut closed it for now waiting to see what to do when the new add-ons system is in place. anyway the situation is not exactly the same since teamViewer is a supported application though I cannot maintain the add-on since I don't use it and I needed visual feedback to develop more labels or features, and people didn't provide it.

Cheers

**Comment by ABuffEr** [comment]
Hi,
I have seen, perfect for me :)

**Comment by feerrenrut** [comment]
I think the [binary should remain](https://github.com/nvaccess/addonFiles) since the [legacy addon page still refers to it](https://addons.nvda-project.org/addons/bitChe.en.html).

**Review by feerrenrut — APPROVED** [review]

**Comment by feerrenrut** [comment]
I have reverted this PR, so the legacy version can still be downloaded.

**Pull request merged**
