### PR TITLE
New version 8.8 of Weather_Plus

### PR DESCRIPTION
**Pull request by ruifontes**
New version 8.8 of Weather_Plus
Avoid opening dialogs on secure screens, so not possible to import/export cities, update sounds or the add-on...

### Release information
- Name (Example, Add-on Updater): 
- Author (example, Your Name): 
- Repo (example, https://github.com/yourname/addonName): 
- Version (example, 21.07): 
- Update channel (example, stable, dev or stable and dev): 
- NVDA compatibility (example, 2021.1 and beyond):

### CODE REVIEW

**Comment by ruifontes** [comment]
Closing due to conflicted files...

**Comment by ruifontes** [comment]
Release information
• Name: Weather_Plus
• Author: Adriano Barbieri <adrianobarb@yahoo.it>
• Repo: https://github.com/ruifontes/Weather_Plus
• Version: 8.8
• Update channel: stable
• NVDA compatibility: 2017.3 and beyond
Changelog (mention changes in separate lines starting with dash space)
- Avoid opening dialogs on secure screens, so not possible to import/export cities, update sounds or the add-on...

**Comment by nvdaes** [comment]
@ruifontes, seems that this branch has conflicts. Can you fix them?

**Comment by CyrilleB79** [comment]
@ruifontes, since you are not the author of this add-on, could you indicate explicitely if you ask this update on behalf of the author?
Thanks.

**Comment by nvdaes** [comment]
Hello: the author of this add-on, Adriano Barbieri, has requested me to update the link on the website. He has sent me a private email for this. So, if this PR is not addressed, I'll create a new one and it could be closed if this one is approved before.

**Comment by CyrilleB79** [comment]
@ruifontes, #264 has been merged.
Could you close this PR please? Thanks!

**Pull request closed without merging**
