### PR TITLE
Add-on Updater 20.12.1

### PR DESCRIPTION
**Pull request by josephsl**
Hi,

This release prepares Add-on Updater to incorporate NVDA Core PR 11909 (winVersion.WinVersion class):

## Release information:

* Name: Add-on Updater
* Author: Joseph Lee
* Repo: https://github.com/josephsl/addonupdater
* Version: 20.12.1
8 Release branch: 20.12.x
* Commit: e525627e2f624ce741e26b360db7be92157571e7
* Update channel: stable

Changelog: prepares Add-on Updater to support winVersion.WinVersion class, specifically, comparing minimum Windows version for add-on updates.

Thanks.

### CODE REVIEW

**Comment by nvdaes** [comment]
Hi @Josephsl, just in case, in a spanish mailing list there are people talking about addonUpdater, not showing the right version of clock. There is a discussion, so I am not sure, but the last message says that addonUpdater should offer a different version. I don"t use these two add-ons, so I just comment in case you need to fix something before this is posted.

**Comment by josephsl** [comment]
Hi, if a new version of Clock add-on was released, the community should be notified so it can be released through add-on files repo. Which version of this add-on is in use by Spanish users? If it is something the community doesn’t know, then it is not really an Add-on Updater issue. Thanks.

**Comment by nvdaes** [comment]
Seeing messages of international and spanish mailing list, as well as
clock add-on on the website, I understand that the problem is not in
add-on updater itself, and I suppose that at least for now it's
difficult to detect if the installed version of an add-on was
downloaded from the server to skip updates in case it was downloaded
from a different source.
Thanks

2020-12-12 9:50 GMT+01:00, nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
Hi, I think this was posted on the add-ons mailing list, but not
updated in addon files. The used version seems to be this:

http://cyber25.free.fr/nvda-addons/clock-20.01-dev.nvda-addon

Messages on the spanish mailing list:

https://nvdaes.groups.io/g/lista/message/1864

2020-12-12 17:07 GMT+01:00, Joseph Lee <notifications@github.com>:

**Comment by josephsl** [comment]
Hi, yep, in this case, it’s not Add-on Updater. Thanks.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
