### PR TITLE
dayOfTheWeek, mp3DirectCut-and sayCurrentKeyboardLanguage 21.09-dev

### PR DESCRIPTION
**Pull request by abdel792**
### Release information
- Name: dayOfTheWeek
- Author: Abdel
- Repo: https://github.com/abdel792/dayOfTheWeek
- Version: 21.09-dev
- Update channel: dev
- NVDA compatibility: 2014.3 and beyond

### Changelog (mention changes in separate lines starting with dash space)

- Updated version and L10N, as well as compatibility metadata.

### CODE REVIEW

**Comment by abdel792** [comment]
### Release information
- Name (Example, Add-on Updater): mp3DirectCut
- Author (example, Your Name): Abdel
- Repo (example, https://github.com/yourname/addonName): https://github.com/abdel792/dayOfTheWeek
- Version (example, 21.07): 21.09-dev
- Update channel (example, stable, dev or stable and dev): dev
- NVDA compatibility (example, 2021.1 and beyond): 2016.4 to 2021.1

### Changelog (mention changes in separate lines starting with dash space)

- Updated version, as well as compatibility metadata.

### Additional information

**Comment by abdel792** [comment]
### Release information
- Name (Example, Add-on Updater): sayCurrentKeyboardLanguage
- Author (example, Your Name): Abdel
- Repo (example, https://github.com/yourname/addonName): https://github.com/abdel792/dayOfTheWeek
- Version (example, 21.07): 21.09-dev
- Update channel (example, stable, dev or stable and dev): dev
- NVDA compatibility (example, 2021.1 and beyond): 2016.4 to 2021.1

### Changelog (mention changes in separate lines starting with dash space)

- Updated version, as well as compatibility metadata.

### Additional information

**Review by nvdaes — APPROVED** [review]

**Comment by abdel792** [comment]
Thanks a lot @nvdaes for your approval.

If it is necessary to separate the PRs into 3, I could try the operation again.

**Comment by abdel792** [comment]
I just recreated 3 separate PRs for these 3 add-ons, so I'm closing this one.

**Pull request closed without merging**
