### PR TITLE
new add-on, Enhanced phonetic reading.

### PR DESCRIPTION
**Pull request by davidacm**
### Release information
- Name: Enhanced phonetic reading
- Author: David CM
- Repo: https://github.com/davidacm/enhancedphoneticreading
- Version: 1.0 and 1.1.1-dev
- Update channel: stable and dev
- NVDA compatibility: 2018.3 to 2021.3.1

### Changelog

version 1.1.1-dev
- updated the way of using timers, now wx.CallLater is used instead. This should fix an incompatibility with bluetoothAudio add-on.
- Changed the whay to save the delay time, now in ms.

### Additional information

This add-on add the feature of delayed descriptions to NVDA. Announce the character description for the last read character after n milliseconds when the character was read by character review commands, E.G. left and right arrow keys, left, current or right character review commands, ETC.  
Also can be configured to read instant character descriptions. Read the character description instead of the current character. This feature must be enabled or disabled manually and will be deactivated when NVDA is closed.

This add-on is old and well known but is not available in the central repo I think. Its very useful for many people, so, it should be included here.
Dev version is because of an incompatibility with bluetoothAudio add-on, then I used wx.CallLater, but I don't know if this may generate issues to NVDA,need more testing.

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Hello @davidacm .
These comments don't affect the review. Anyway:

- If you need to register this or other add-ons on the translation system, you can get info about how to request this on [mrconfig repo](https://github.com/nvaccess/mrconfig)
- I've observed that the channel for the stable version of this add-on is set to dev. I don't know if this is or not relevant, but this field doesn't affect NVDAitself and I don't have to consider it in the review. I don't know if this affects addon updater by @josephsl 
- To update the documentation of this or other add-ons on the website, you can request an invitation if you aren't a member of the translations team, or let us know to update it, considering that format of readmes maybe changed to follow the conventions of the website, like including download links.

Thanks

**Comment by josephsl** [comment]
Hi, actually, update channel key does affect Add-on Updater since putting “dev” will force Add-on Updater to add a “-dev” suffix to the add-on key string when retrieving version info from add-on files database. It also impacts the current design of Add-on Datastore since users would be asked to check for beta add-ons if wishing to install this add-on. My advice at this time is to change the update channel to “None” (without quotes) so at least Add-on Updater can check for stable channel releases. Thanks.

**Comment by nvdaes** [comment]
Thanks for clarification Joseph.
Anyway, about the store, the channel would be set in a json file and,
according to current plans, I think it can be stable or beta, not dev:

https://github.com/nvaccess/addon-datastore-validation/blob/main/_validate/addonVersion_schema.json


2022-01-03 8:02 GMT+01:00, Joseph Lee ***@***.***>:

**Comment by davidacm** [comment]
Thanks for the comments! As a quick fix, For now I updated the stable link file (URL is the same) now the channel is set to stable. Sorry, my mistake, I forgot to change it. I will keep this in mind for next updates.

@nvdaes thanks for the links and suggestions, I will read them. :)

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Thanks @davidacm. Generally when channel is stable is set to None. This is much better reviewed by @josephsl , who knows the behavior of this for addonUpdater.

**Pull request merged**
