### PR TITLE
Add-on Updater 21.05.1

### PR DESCRIPTION
**Pull request by josephsl**
## Release information:

* Name: Add-on Updater
* Author: Joseph Lee
* Repo: https://github.com/josephsl/addonUpdater
* Version: 21.05.1
* Update channel: stable
* NVDA compatibility: 2020.4 and beyond
* SHA256: aca857e05f3e483f50a77412c6c896fe7fe2fb5f5e4ee8e2c5b09ebb2c30ec6f

Changelog: localization updates, NVDA compatibility update.

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Hello @feerrenrut , I have reviewed diffs (with git log -p until April), manifest and URL. Thanks

**Comment by nvdaes** [comment]
Also, as mentioned in this [message on the add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/message/15193), I think this shouldn't be merged until NVDA 2021.1 is released.
Anyway I'm not sure, so I requested your review and will adjust my work about approving pull request on this repo according to your procedure with this and add-ons compatible with NVDA 2020.4, @feerrenrut

**Comment by feerrenrut** [comment]
Now that the Addon API is final** it is acceptable for add-ons to be released claiming to be compatible with this version of the API. Ideally all addons are made compatible and released before the release of NVDA 2021.1.

** Best effort guarantee only.

@nvdaes please continue to review these changes. If you approve them, I'll merge the changes in.

**Comment by nvdaes** [comment]
I approve this. Please merge (from mobile).

**Pull request merged**
