### PR TITLE
New add-on cursorLocator 1.0.1

### PR DESCRIPTION
**Pull request by nvdaes**
### Release information
- Name: Cursor Locator
- Author: Noelia Ruiz Martínez, Sergio Gómez Codina
- Repo: https://github.com/nvdaes/cursorLocator
- Version: 1.0.1
- Update channel: stable
- NVDA compatibility: 2022.1 and beyond
- SHA-256: 3b784c9c3bd58d9d1d29b97c415965edaa1900590c31b192ce4c513acd72f597
### Changelog
- Initial version, with addition of @sergiogomez31 as an author

### Additional information

This add-on makes possible to know the position of the system caret respect to the start of the current line, while typing to add text in multiline controls.

This feature deppends on the visual appearance of applications. Therefore, you may need to disable line adjustment or configure the add-on for different programs.

## Cursor Locator settings ##

This panel is available from NVDA's menu, Preferences submenu, Settings dialog.

It provides the following options:

* Report start of line: When this control is checked, a low tone will announce if the caret is at the start of the current line while text is been added. (Checked by default).
* Report line length: You can type or choose a line length (number of characters between 0 and 600), which will be announced by a hight tone when it's reached. (The default value is 80 characters).
* Pitch of sound for start of line: You can type or select a value between 20 and 20000. (The default value is 400 hertzs).
* Length of sound for start of line: You can type or select a value between 20 and 2000. (The default value is 50 milliseconds).
* Test sound for start of line: Press this button to test the configured sound for start of line.
* Pitch of sound for end of line: You can type or select a value between 20 and 20000. (The default value is 1000 hertzs).
* Length of sound for end of line: You can type or select a value between 20 and 2000. (The default value is 50 milliseconds).
* Test sound for end of line: Press this button to test the configured sound for end of line.

## Commands ##

You can modify the gestures to the following commands trought the NVDA's menu, Preferences submenu, Input gestures dialog:

* NVDA+control+shift+l: When possible, reports the lenght of the current line (System caret category).
* Not assigned: Shows the Cursor Locator settings dialog (Config category).

### CODE REVIEW

**Review by josephsl — APPROVED** [review]

**Comment by nvdaes** [comment]
@josephsl : you may want to review this again.
@feerrenrut : I saw that you update this PR with commits from master and I've done the same before editing this, to add @sergiogomez31 as an author.
Thanks

**Review by josephsl — APPROVED** [review]
While all lowercase for add-on key is the norm, I'm fine with what we have here as long as people can download the add-on.

**Comment by nvdaes** [comment]
oh, thanks Joseph. For now i will share the link on the mmailing list. I didn"t realise about the norm on lowercase though this is valid. This maybe merged when NVDA 2022.-1 or an rc is published

Enviado desde mi iPhone

**Comment by josephsl** [comment]
Hi, think about add-ons such as Outlook Extended where get.php lists it under “outlookextended” (no camel case). Thanks.

**Pull request merged**
