### PR TITLE
Update Bluetooth Audio

### PR DESCRIPTION
**Pull request by mltony**
## Bluetooth Audio v1.4
* Repo: https://github.com/mltony/nvda-bluetooth-audio
* Compatibility: NVDA 2021
* Supports dynamic switching of audio device.
* Supports playing white noise.
* Redesigned multithreading code.
* Bugfixes

### CODE REVIEW

**Review by nvdaes — CHANGES_REQUESTED** [review]
Hello @mltony 
Please:
- As mentioned in the readme of this repo:

> Only once the first NVDA Beta is released will the API be considered frozen, therefore 'lastTested' should not be set to that version until after the beta.

- In order to provide useful info in this PR, please fill-in the template with release information.

I'll try to review again this and other pull requests created by you when this can be fixed.

Thanks

**Comment by mltony** [comment]
@nvdaes, as I mentioned before I only have time around New Year to work on my add-ons. Since you have so strict requirements regarding compatibility - let's drop 2022 compatibility. I mark my add-ons to be at 2021 level compatibility.

**Review by nvdaes — COMMENTED** [review]
Hi @mltony, thanks for your reply. I'll approve this PR when add-on manifest matches compatibility requirements.
Happy new year!

**Comment by josephsl** [comment]
Hi,

Update: NVDA 2022.1 beta 1 was tagged, awaiting official release before approving this pull request.

Thanks.

**Comment by josephsl** [comment]
Hi,

April update: if things go well, this add-on update will be approved for distribution this weekend.

Thanks.

**Review by josephsl — APPROVED** [review]

**Comment by nvdaes** [comment]
Hello, as agreed, considering that @Josephsl has a better knowledge of Tony"s add-ons, I leave them on his hands.

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
