### PR TITLE
Register Ignore Blanks Indentation Reporting

### PR DESCRIPTION
**Pull request by SamKacer**
### Release information
- Name : Ignore Blanks Indentation Reporting
- Author : Samuel Kacer
- Repo : https://github.com/SamKacer/IgnoreBlanksIndentation
- Version : 0.1
- Update channel : stable
- NVDA compatibility : 2021.1

### Changelog (mention changes in separate lines starting with dash space)

- Initial release

### Additional information

My first contribution. Apologies for mistakes made due to inexperience.

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]
Reviewed in this [Thread on the add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/topic/84381508#16276) by @CyrilleB79. I completed the review since Cyrille is not available at this moment. Hope this is OK for you, Cyrille. Feel free to provide any feedback.

@SamKacer, as you know, you can create an issue in nvaccess/mrconfig repo in case you want get the add-on registered in the NVDA and add-ons translation system, so the translation team can take care easily. Read documentation in mrconfig repo for more info. If you decide to register the add-on, please let us know on the add-ons mailing list so we can fork your repo in nvdaaddons GitHub organization, after you have created the required stable branch.
Also, the website will need to be updated when this PR is merged. If you want to do it yourself, you need an invitation to the SVN repo and you can request it on the translations mailing list in case you don't belong to the team at this moment.

**Comment by SamKacer** [comment]
> @SamKacer, as you know, you can create an issue in nvaccess/mrconfig repo in case you want get the add-on registered in the NVDA and add-ons translation system, so the translation team can take care easily. Read documentation in mrconfig repo for more info. If you decide to register the add-on, please let us know on the add-ons mailing list so we can fork your repo in nvdaaddons GitHub organization, after you have created the required stable branch.

I think for now, it isn't worth registering for translation, since it doesn't introduce any new commands, settings items, or messages. The only thing that would be worth translating would be the readme. Also, since it is programming-focused, I suspect anyone interested in it will be an english speaker, since that is pretty much a prerequisite for learning to program in most countries. 

> Also, the website will need to be updated when this PR is merged. If you want to do it yourself, you need an invitation to the SVN repo and you can request it on the translations mailing list in case you don't belong to the team at this moment.

Is this in relation to registering the addon for translation, or if I am not registering it for translation for now, can I ignore this part?

**Comment by nvdaes** [comment]
@SamKacer, regarding your question:


>Also, the website will need to be updated when this PR is merged. If you want to do it yourself, you need an invitation to the SVN repo and you can request it on the translations mailing list in case you don't belong to the team at this moment.
Is this in relation to registering the addon for translation, or if I am not registering it for translation for now, can I ignore this part?

This is not related to the registration in the translations system. addonfiles repo is used to provide links (generally direct download links) on the community add-ons website. The website is managed by the translation team. When this PR is merged, we have to copy (with some small modifications) your readme.md in the SVN repo. Then, the translation system, even if you don't register the add-on, will generate .po files so translators can provide translations for the different languages supported by the website. I can do it for you this time if you don't want to request an invitation to the SVN Repo.
The registration in the system makes possible that:
1. Documentation translated on the website, previously converted to .po files, is converted again to .md files and automatically copied to your add-on into the doc subfolder.
2. The manifest.ini and other messages, if any, when translated, are copied into the locale folder of the add-on so people can see the translated messages in the add-on gui.


Just let me know if you want me to take care of sending the readme.md to the website.

Hope this helps.

**Review by feerrenrut — APPROVED** [review]

**Comment by SamKacer** [comment]
@nvdaes thanks, if you wouldn't mind updating the website this time, I would really appreciate it. just having a really hectic week.
I will be putting up a update request today or tomorrow, since a bug has been discovered. Basically, the addon causes math content to not be readable. fortunately, I have a fix, just waiting for feedback.

**Comment by nvdaes** [comment]
OK, then I'll wait for the new PR with the fixed version and will create the documentation on the website.
Have a good wek.

**Comment by CyrilleB79** [comment]
> Reviewed in this [Thread on the add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/topic/84381508#16276) by @CyrilleB79. I completed the review since Cyrille is not available at this moment. Hope this is OK for you, Cyrille. Feel free to provide any feedback.

As confirmed today by me on the add-on mailing list, all is fine for me.

**Comment by nvdaes** [comment]
Thanks @CyrilleB79 
😄

**Pull request merged**
