### PR TITLE
Remote 2.4

### PR DESCRIPTION
**Pull request by josephsl**
### Release information
- Name: NVDA Remote
- Author: Tyler Spivey <tspivey@pcdesk.net>, Christopher Toth <q@q-continuum.net>
- Repo: https://github.com/nvdaremote/nvdaremote
- Version: 2.4
- Update channel: stable
- NVDA compatibility: 2019.3 to 2021.1
- Sha256: 0a348440582300c8185696d717603a4c107aae483b1b7eef63e7e5d22a613cd6

### Changelog (mention changes in separate lines starting with dash space)
Compatible with NVDA 2021.1.

### CODE REVIEW

**Comment by josephsl** [comment]
Hi,

Requesting a high priority review please.

Thanks.

**Comment by josephsl** [comment]
CC @CToth, @TSpivey

**Comment by ctoth** [comment]
Oh man, does this not have any form of hash to verify the files served from the websites are the actual files? It makes me profoundly nervous that I could just swap out the link to remote 2.4 with another addon and there would be no user-visible way to tell.

**Comment by josephsl** [comment]
Hi, that’s what SHA256 field is for. Thanks.

**Review by nvdaes — COMMENTED** [review]
Hello, the documentation title is related to version 2.3. This is not consistent with the real version. Do you have plans to change it mentioning that the add-on is compatible with NVDA 2021.1?

Also, note that in the add-ons website there is not a direct link to this add-on, thought it's present in this repo (add-on files).
@feerrenrut , as a contributor of this add-on and manager of this repo, can you provide feedback on this please?
The manifest and URL are right, but I think that these questions should be answered before approving this PR.

**Comment by feerrenrut** [comment]
@ctoth agreed, this is one of the motivations for a replacement add-on system we are currently working on, it solves this issue. The overview can be found here: https://github.com/nvaccess/addon-store-submission/blob/master/README.md
However, the same is true for the NVDA remote website, the addon binary could be replaced with no way to check.

@nvdaes Yes, you are right. The released version is 2.4, but the version in the [readme on github](https://github.com/NVDARemote/NVDARemote/blob/master/readme.md) is 2.3. There are also no release notes for 2.4.

At the end of the day this is the responsibility of the add-on authors to make a coherent add-on.
@nvdaes I'd recommend raising an issue on their repository.

**Review by feerrenrut — APPROVED** [review]
As mentioned by @nvdaes, this won't appear on https://addons.nvda-project.org/addons/nvdaremote.en.html

But for completeness, I'll accept the change.

**Pull request merged**
