### PR TITLE
Resource Monitor 21.10

### PR DESCRIPTION
**Pull request by josephsl**
### Release information
- Name: Resource Monitor
- Author: Alex Hall, Joseph Lee, beqa gozalishvili, Tuukka Ojala, Ethin Probst and other contributors
- Repo: https://github.com/josephsl/resourcemonitor
- Version: 21.10
- Update channel: stable
- NVDA compatibility: 2021.1 and later
- Sha256: b0183e348d11152b02b15cf70166fdffdfeaa7684df315ba238ca572730221af

### Changelog (mention changes in separate lines starting with dash space)
- Requires NVDA 2021.1 or later.

### Additional information
This is the second to last planned release of Resource Monitor under Joseph Lee's maintenance. The final release under my maintenance will be made in January 2022.

### CODE REVIEW

**Review by nvdaes — COMMENTED** [review]
Hi, I think that the manifest should be changed to specify minimum NVDA version = 2021.2. Currently 2021.1 is required, but according to release info and changelog, this maybe a mistake, right?

**Comment by josephsl** [comment]
Hi,

Actually, manifest is correct - updated the initial comment to reflect this oversight.

**Comment by nvdaes** [comment]
Though the comment has been edited, the changelog reflects that NVDA 2021.2 is required, but this is not true according to manifest.

**Comment by josephsl** [comment]
Hi, resolved – looks like I need to stop releasing many add-ons at once in a single day… Thanks for reminding me to fix this.

**Comment by nvdaes** [comment]
Hi, is this releae needed?
The version posted on the website claims for compatibility: NVDA 2021.1 or later.

**Comment by josephsl** [comment]
Hi, I would say yes for now as the changelog may offer additional explanations as to why a certain NVDA version is needed. Thanks.

**Comment by nvdaes** [comment]
The offered explanation is the change of the minimum required version, what hasn't happened. Anyway I'll approve this since the manifest is right, but may not be needed if this is the only change

**Review by nvdaes — APPROVED** [review]

**Comment by josephsl** [comment]
Hi, I feel we (add-ons community) can do a better job in documenting our changes… Thanks.

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
