### PR TITLE
sayCurrentKeyboardLanguage-22.06

### PR DESCRIPTION
**Pull request by abdel792**
### Release information
- Name: sayCurrentKeyboardLanguage
- Author: Abdel
- Repo: https://github.com/abdel792/sayCurrentKeyboardLanguage
- Version: 22.06
- Update channel: stable
- NVDA compatibility: 2014.3 and beyond

### Changelog

- Updated lastTestedNVDAVersion to 2022.1 in manifest file;
- Updated translations.

### CODE REVIEW

**Comment by abdel792** [comment]
Thanks @nvdaes for your approval.

**Comment by abdel792** [comment]
Thanks @feerrenrut for merging.

**Comment by XLTechie** [comment]
Incorporated into Add-on Updater as of about 06:00 EDT today.

**Comment by abdel792** [comment]
Thanks @XLTechie,

Could you also incorporate [mp3DirectCut-22.06](https://github.com/nvaccess/addonfiles/pull/369)?

Thanks in advance.

**Comment by XLTechie** [comment]
> Could you also incorporate mp3DirectCut-22.06?

I updated compatibility for mp3DirectCut, dayOfTheWeek, 
and sayCurrentKeyboardLanguage all at the same time. Sorry if I didn't comment 
to that effect.

**Comment by abdel792** [comment]
Okay @XLTechie, thanks.

**Pull request merged**
