### PR TITLE
Added sleep.

### PR DESCRIPTION
**Pull request by TheQuinbox**
### Release information
- Name: Sleep
- Author : Originally by Derek Riemer, updated by Quin Marilyn
- Repo: https://www.github.com/TheQUinbox/sleep
- Version: 2021.1
- Update channel: Stable
- NVDA compatibility: 2021.1.0 and beyond

### Changelog (mention changes in separate lines starting with dash space)

- Updated to work with NVDA 2021.1
- Cleaner code.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
Has this add-on been reviewed? If it was please link to the appropriate conversation.

**Comment by jmdaweb** [comment]
Of course, the answer is no, and this is the second time. Please, subscribe to the [NVDA-addons mailing list](https://nvda-addons.groups.io/g/nvda-addons), send an e-mail introducing this add-on and request a basic review. The pull request goes after passing that review.
Regards.

**Comment by nvdaes** [comment]
@TheQuinbox, can you mention the thread of the add-ons mailing list where this was posted or reviewed? For now basic review is required before posting a new add-on on the website.
Also, you mentioned that this add-on was originally created by a different author. Please, mention the author GitHub account so this person can be notified about this.
Thanks.

**Comment by TheQuinbox** [comment]
Hi,
I thought my first addon was directly reviewed in the PR? Whatever, doesn't matter. I'll try to get this reviewed, then open another PR. And yes, I did notify the author.

**Comment by nvdaes** [comment]
Yes, in fact your previous PR was reviewed directly on GitHub, and
this was supported by @feerrenrut.

https://github.com/nvaccess/addonFiles/pull/81

Anyway this is not the usual procedure, and the Sleep add-on, if it's
what I think, was posted on the add-on mailing list in 2016. I
remembed it and searched the thread saved in my Gmail folder. So you
may want to follow the usual procedure. Anyway, as an owner of the
mailing list, I'll comment this with the other owners (NV Access) to
know what to do in future similar situations, given that the add-on
store submission is in progress, NV Access are now responsible for
this repo and that human review, according to plans for the future
store, will not be required.
Kind regards

2021-09-13 12:48 GMT+02:00, Quin ***@***.***>:

**Comment by TheQuinbox** [comment]
Okay, thanks. Sorry for the confusion.

**Pull request closed without merging**
