### PR TITLE
Update emoticons to 15.0

### PR DESCRIPTION
**Pull request by nvdaes**
### Release information
- Name: Emoticons
- Author: Chris Leo, Noelia Ruiz Martínez, Mesar Hameed, Francisco Javier Estrada Martínez
- Repo: https://github.com/nvdaes/emoticons
- Version: 15.0
- Update channel: stable
- NVDA compatibility: 2022.1 and beyond
- SHA-256: 37d83c82e5ff52ddcef716d0f93d46608cdb2b63a2ee4ad51061a4fdea96946f  
### Changelog (mention changes in separate lines starting with dash space)
-Requires NVDA 2022.1 or later.
- Cannot be run on secure screens.

### CODE REVIEW

**Review by josephsl — APPROVED** [review]

**Comment by nvdaes** [comment]
@CyrilleB79 [comment](https://github.com/nvaccess/addonFiles/pull/326#issuecomment-1127416625)

@nvdaes and @josephsl for next time:
Please do not accept PRs on this repo for add-ons only compatible with next stable release.

Hi Cyrille: I explained that I'll send pull requests before the stable release of NVDA in the 
[thread about NVDA 2022.1rc1](https://nvda-addons.groups.io/g/nvda-addons/message/18773). This is to give time to reviewers. Also, consider that Reef accepted tis too.
Thanks

**Comment by josephsl** [comment]
Hi, a better approach: in the “additional context” section, do note that these PR’s should be accepted only when the stable version is released. This should also apply to the future datastore repo since anyone can create PR’s at anytime. I approved it early due to a huge schedule conflict that can arise in the middle of the week at which point I might not be able to approve them on time. As for the thread mentioned, I understand that manifest edit was performed as a workaround, something I do not encourage unless the add-on is known to work with earlier releases which is clearly not the case with these PR’s. Thanks.

**Comment by josephsl** [comment]
Hi, in this case, I will take the blame for this mess as I was responsible for approving them (hopefully that won’t add a headache to what may turn out to be a stressful finals week; at least this confirms that I seriously need a break from everything NVDA for at least a few weeks…). For now at least Add-on Updater will not offer the newly approved updates to anyone running NVDA 2021.3.x. Thanks.

**Comment by feerrenrut** [comment]
@CyrilleB79 I'm not going to go an check the manifests manually. I can't spend time in that way. I'll merge these PR's if either @josephsl or @nvdaes has approved them. I've previously made suggestions on how to review these and said I won't be looking at the details of the add-on anymore, but perhaps this wasn't clear.

I only check that the change is what it says it is (adjusting only the one add-on entry) and to ensure the change isn't malicious.

This will is checked for automatically in the new add-on store, but for now add-on authors need to take responsibility over this.

**Comment by nvdaes** [comment]
Cyrille, my intention is not prioritizing reviewrs over users. Otherwise, I considered that rc period maybe good to send pull requests even for add-ons compatible with the next stable version, so that when NVDA 2021.1 (the stable version) is released, users can get the add-ons.
The compatibility is reflected in the description of the pull request. For requirements, as you can see in the readme of this repo, the only requirement is:

> ◦ Only once the first NVDA Beta is released will the API be considered frozen, therefore 'lastTested' should not be set to that version until after the beta.
Releases 

So, we've followed this. Anyway, you maybe right and I understand your point of view. But, as mentioned, I commented it on the add-ons mailing list and I haven't received any objections.
Cheers

**Pull request merged**
