### PR TITLE
Update clipspeak add-on

### PR DESCRIPTION
**Pull request by ruifontes**
### Release information
- Name: clipspeak
- AuthorRui Fontes, Ângelo Abrantes and Abel Passos Júnior, based on the work of Damien Sykes-Lindley
- Repo: https://github.com/ruifontes/clipspeak
- Version: 2022.03
- Update channel: stable
- NVDA compatibility: 2019.3 and beyond

### Changelog
- Compatibility with NVDA 2022.1;
- Mechanisme of automatic update, set to do not check by default;
- Option to just announce copy/cut/paste or also what is being copied/cutted/pasted;
- Improved keystrokes validity.

### Additional information
- New maintainer.

### CODE REVIEW

**Review by josephsl — APPROVED** [review]

**Review by nvdaes — COMMENTED** [review]
@ruifontes, I know that this has been approved, but since this add-on has not been updated on the website time ago, as far as I know, I've looked at it.
Question: Why is this line in in diffs of get.php?

' +	"appdict" => "https://github.com/ruifontes/applicationDictionary-/releases/download/2022.03.26/applicationDictionary-2022.03.26.nvda-addon",'
Maybe you didn't update your master branch or something.

Also, I find some minor issues in the add-on, easy to check:

- The add-on seems to save settings always in normal configuration, not in specific profiles. Fix me if I'm wrong. But the settings panel appears for all profiles, and this maybe confusing.
- - I open the NVDA's log viewer, press control+x and the add-on says cut and can read the text contained in the clipboard,even when the cut operation is not performed, and in fact the text contained in the clipboard, selected from other application, can be pasted multiple times.
- I'm just seen this now, so I'm be wrong, so let me know if I should register this issues on your repo or something.

**Comment by ruifontes** [comment]
Hi Noelia!

You wrote:
Question: Why is this line in in diffs of get.php? 
' + "appdict" => "https://github.com/ruifontes/applicationDictionary-/releases/download/2022.03.26/applicationDictionary-2022.03.26.nvda-addon",'
Maybe you didn't update your master branch or something.

I don't know!
I try to remember to update my repo before creating any branch...
But maybe something had gone wrong...
I need to do something now?


Noelia wrote:
The add-on seems to save settings always in normal configuration, not in specific profiles. Fix me if I'm wrong. But the settings panel appears for all profiles, and this maybe confusing.

That is a part of NVDA I do not yet understand very well...
If somebody can help me to fix that, I will be pleased!


Noelia wrote:
• 
◦ I open the NVDA's log viewer, press control+x and the add-on says cut and can read the text contained in the clipboard,even when the cut operation is not performed, and in fact the text contained in the clipboard, selected from other application, can be pasted multiple times.

Will be corrected next version...

Rui Fontes

**Comment by nvdaes** [comment]
Ruifontes wrote:

> I try to remember to update my repo before creating any branch...
But maybe something had gone wrong...

I advice you to do:

```git checkout master
git remote -v  # To see the name and URL associated with each remote. 
git branch -u origin/master  # Supposing that origin is set to NV Access repo, to synchronize your master branch with master branch of NV Access repo.
git pull  # To update
```
Hope this helps.
About profiles, if you want I can create a PR in your repo this weekend, so that the say copy cut paste option is available for specific profiles.

**Comment by ruifontes** [comment]
Hola Noelia!

Às 18:30 de 29/03/2022, Noelia Ruiz Martínez escreveu:
I advice you to do: 
git remote -v  # To see the name and URL associated with each remote. 
git branch -u origin/master  # Supposing that origin is set to NV Access repo, to synchronize your master branch with master branch of NV Access repo.
git pull  # To update
Hope this helps.

Thanks but I use GitHub Desktop, a graphic interface to do that...


Noelia Ruiz Martínez escreveu:
About profiles, if you want I can create a PR in your repo this weekend, so that the say copy cut paste option is available for specific profiles.

Many thanks, but I think is better to be a global option and not a specific profile option.
I am not seeing none use case to use it in a profile...
What do you think?

**Comment by nvdaes** [comment]
Hello, about syncrhonize your branch to create PRs with nvda/master, you should do it. Reviewers may have difficulties to approve your PRs if for example seems that you're sending two different add-ons..
About specific profiles for the report just in copy/cut/paste options, I don't see any reason to prevent users to set different values for this option for specific profiles. But it's OK if uou preferto have just a global option. In this case, I advice you to disable this option when the settings dialog is opened if a specific profile is active, or at least mention that the option cannot be set for profiles in the readme.
In case you want me to help with something about this, I'm still availablethis weekend, just if you need it.

**Review by josephsl — CHANGES_REQUESTED** [review]
Please address at least branch merge comment from Noelia, and then we will consider approving it for wider distribution.

**Comment by josephsl** [comment]
Hi,

It appears Application Dictionary is not present in get.php with the latest commit. Once that's restored, it will be ready for approval.

Thanks.

**Comment by nvdaes** [comment]
> ruifontes commented 10 hours ago 
Noelia, if you think it is better be specific profile, please go ahead...
I will learn with you how to do it...

OK, I'll create  PR for your repo this weekend or before. Then I'll request you to review it.

**Comment by ruifontes** [comment]
Closing this PR.
I will create a new one with all comments resolved.
Thanks!

**Pull request closed without merging**
