### PR TITLE
Update ColumnsReview to 3.0 stable and 20210910 dev

### PR DESCRIPTION
**Pull request by ABuffEr**
### Release information

- Name: Columns Review
- Author: @ABuffEr , @lukaszgo1 , other contributors
- Repo: https://github.com/ABuffEr/columnsReview
- Version: 3.0 and 20210910-dev
- Update channel: stable and dev
- NVDA compatibility: 2017.3 and beyond

### Additional information

After a long, long time, and some users requests (hi @CyrilleB79  😉), a new official and stable version is finally here.

Dev is like stable, at the moment, but contains unofficial translations (largely outdated in this phase). Stable branch should be already ok for translation system.

I almost completely rewrote the documentation, so even English presentation should be updated on website.

Thanks to all for work and support.

### CODE REVIEW

**Comment by lukaszgo1** [comment]
Looks fine to me. Any particular reason for adding two assets to one release rather than just creating one stable release and one prerelease for a dev version?

**Review by nvdaes — APPROVED** [review]
@ABuffEr , I think you can manage the documentation on the website your self. Otherwise let me know.

**Comment by ABuffEr** [comment]
Hi @lukaszgo1 ,
the only reason is that I don't particularly like the idea to have a (pre)release for each dev version, being very frequent sometimes. So, after looking around, I noticed [WinTenApps solution](https://github.com/josephsl/wintenApps/releases/), to group dev version under stable tag.

**Comment by ABuffEr** [comment]
> @ABuffEr , I think you can manage the documentation on the website your self. Otherwise let me know.

Hi @nvdaes ,
is still it the SVN repo on Assembla, right? Yes, I have to remember SVN procedure, but I should be able to do it, anyway.

**Comment by nvdaes** [comment]
Yes, the documentation is in Assembla. Checkout the repo, go to website bar addons, and proceed. I"m from mobile now, where I"ve received the GitHub notification, in case the format is different.

**Comment by lukaszgo1** [comment]
I recall someone from the Spanish community (I believe it was @jmdaweb ) asked to create a separate GitHub release  for  each new version of add-ons since they're subscribing to the releases for some repositories and rely on the notification to announce new versions to their community before they hit the official website. In the ideal case this would not be necessary and add-ons would be posted on the official page with no delay, but we are far from such ideal workflow yet.

**Comment by ABuffEr** [comment]
> I recall someone from the Spanish community (I believe it was @jmdaweb ) asked to create a separate GitHub release for each new version of add-ons since they're subscribing to the releases for some repositories and rely on the notification to announce new versions to their community before they hit the official website.

Hmm, ok, I can create separate pre-release under byyyymmdd tag (b = build). Thinking about it, this should create a lot of tags, true, but make easier to investigate problems if occur in new builds, too.
If @nvdaes  agrees, I proceed on my repo and modify this PR accordingly in next hours.

**Comment by nvdaes** [comment]
Íf you modify this PR, I"ll review it. About creating lots of tags, I have a unique tag for pre-releases published weekly by GitHub Actions. Thorium ePUB reader uses a latest tag for continuous testing, with assets for Windows, Linux and Mac, and I toke inspiration from them for this. For Take account that the planned store will require to provide SHA-256 in the metadata (stored in a .json file), and maybe easier to post releases and pre-releases, even generating the SHA-256 for each nvda-addon file, and in this sense maybe less confussing to publish nvda-addon binaries in separate releases. Just thinking in the future. ☺️

Enviado desde mi iPhone

**Comment by jmdaweb** [comment]
Hi,
Yes, I sent that message encouraging developers to use GitHub releases. However, since pull requests are submited to this repo, monitoring add-on releases is as easy as subscribing to pull requests here. For add-ons with a very active workflow and frequent pre-releases, we are waiting for the stable version to announce them. Using releases is particularly helpful for us (and for everyone who wants to stay up to date) with add-ons not registered in the community website.
Regards.

**Review by nvdaes — APPROVED** [review]

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
