### PR TITLE
Resource Monitor 21.04.1

### PR DESCRIPTION
**Pull request by josephsl**
## Release information:

* Name: Resource Monitor
* Author: Alex Hall, Joseph Lee and contributors
* Repo: https://github.com/josephsl/resourcemonitor
* Version: 21.04.1
* Update channel: stable
* NVDA compatibility: 202.4 and later

Changelog: requires NVDA 2020.4, reworked resource info copy mechanism to follow NVDA 2020.4 changes.

Update: 21.04.1 replaces 21.04 with manifest edits (see below discussion).

### CODE REVIEW

**Comment by feerrenrut** [comment]
@josephsl I've noticed that this add-on sets the last tested version to 2021.1 since this version has not reached beta, and the add-on API version has not been set, it is not finalized. This means it could (and likely will) change after your add-on is released. For users of your addon who remain on this version, they are not protected from the potential future changes in API that may come between now and when the 2021.1 API is finalized. 

When we move to the new add-on store, this will be checked and add-on release pre-empting API versions will be rejected. Please could you revert the last tested value to 2020.4 thanks

**Comment by josephsl** [comment]
Hi, I’ll do that with one request: can we turn this check off for dev snapshots of add-ons? Thanks.

**Comment by josephsl** [comment]
Hi,

Done - last tested version is set to 2020.4 and readme was updated.

Thanks.

**Comment by josephsl** [comment]
Hi,

After thinking about last tested version metadata requirement, for now I think it would be better to apply the same metadata check for dev snapshots (please ignore my request above).

Thanks.

**Comment by feerrenrut** [comment]
Ok, I'll ignore it.

But for others who may be interested. On NVDA we will only update the API version numbers (for compatibility breaking releases such as 2021.1) when we do the first beta. This means that dev versions of add-ons can continue to be developed alongside alpha. Only when the beta is reached does the manifest for the dev addon need to be updated.

**Comment by feerrenrut** [comment]
Also with this PR, you'll need to do a new release and update the URL.

**Comment by josephsl** [comment]
Hi, understood – I think we might as well document this as an FAQ entry somewhere. Thanks for clarifications.

**Comment by feerrenrut** [comment]
Perhaps, though this process should be entirely replaced by the add-on store.

**Comment by josephsl** [comment]
Hi, actually, the URL can remain the same – I have updated Resource Monitor based on latest feedback. Thanks.

**Comment by feerrenrut** [comment]
The problem is that the release is tied to a commit, it is like a tag or is a tag. So checking the diff between versions does show these changes. You'd have to delete and recreate the release. Might be better to just do a point one release.

**Comment by josephsl** [comment]
Hi, yep, I’ll create a new tag then. Thanks for the advice.

**Review by feerrenrut — APPROVED** [review]
Thanks @josephsl

**Pull request merged**
