### PR TITLE
NVDA Remote 2.5

### PR DESCRIPTION
**Pull request by josephsl**
### Release information
- Name: NVDA Remote Support
- Author: Christopher Toth, Tyler Spivey
- Repo: https://github.com/nvdaremote/nvdaremote
- Version: 2.5
- Update channel: stable
- NVDA compatibility: 2019.3 and later

### Changelog (mention changes in separate lines starting with dash space)
Based on a tweet from @CToth:

- Compatibility with NVDA 2022.1
- Server history
- Translation updates

### CODE REVIEW

**Comment by josephsl** [comment]
CC @CToth, @TSpivey

**Review by nvdaes — COMMENTED** [review]
@josephsl, I see that this PR is not created by @josephsl: I see that this PR is not created by the add-on authors.. Have they requested you this?
Also, the community add-ons website has a webpage mentioning this add-on with a link to the Remote Support webpage, and addonFiles repo is to provide direct links to .nvda-addon binaries, not provied for this add-on. I don't know if authors of this add-on are interested in providing a direct link on our community website or not. But for the webpage about this add-on, which doesn't include a direct link, what's the purpose of this PR?

The webpage is at

https://addons.nvda-project.org/addons/nvdaremote.en.html

Seems this doesn't make sense.

**Comment by nvdaes** [comment]
Sorly, I realised that this may be used to provide updates via addonUpdater. Anyway, I think that this shouldn"t be approved until clarification about the purpose of this PR, and confirmation from add-on authors.

Enviado desde mi iPhone

**Review by XLTechie — APPROVED** [review]
@josephsl if this is to be a backup, to deal with situations like nvdaremote.com going away for a time (as it did a few weeks ago): then the file should be uploaded directly here, in which case it would be a true backup. Just linking to nvdaremote.com doesn't fulfill the backup function.

That said, having it linked here is still convenient either way, and the former link is to an outdated version.

**Comment by nvdaes** [comment]
@josephsl , I agree with Luke, and also please consider the opinion of authors, who haven't replied here. I think this is a matter of working in a respectful way.

**Comment by jmdaweb** [comment]
Hi,
Sincerely, I don't see any valid reason in this context to wait for authors. The add-on has been properly tagged on GitHub, released in its official website, announced via social networks, so it's publicly available for everyone. Google won't ask you wether your website should be indexed or not in a similar situation.
This only delays even more the PR aprobal and merge. Given the add-on importance, and assuming it has passed all review requirements (manifest and download link), discussions like this one should be avoided or continued after merging it.
Regards.

**Review by jmdaweb — APPROVED** [review]

**Comment by josephsl** [comment]
Hi, that’s why I mentioned both authors in case they would like to talk about it. Tanks.

**Comment by CyrilleB79** [comment]
@jmdaweb wrote:
> Hi, Sincerely, I don't see any valid reason in this context to wait for authors. The add-on has been properly tagged on GitHub, released in its official website, announced via social networks, so it's publicly available for everyone. Google won't ask you wether your website should be indexed or not in a similar situation. This only delays even more the PR aprobal and merge. Given the add-on importance, and assuming it has passed all review requirements (manifest and download link), discussions like this one should be avoided or continued after merging it. Regards.

And @josephsl wrote:
> Hi, that’s why I mentioned both authors in case they would like to talk about it. Tanks.

These two comments clearly denote an evolution on the question to know which add-on should be listed on the community website and available via add-on updater.
Historically, the inclusion or the update of an add-on needed to be asked by the author or on behalf of him.
If this PR is approved, this is not the case anymore:
* Any publicly available add-on can be added or updated on the website (cf. @jmdaweb's comment). On which criteria?
* The author's explicit request is not needed anymore, he is just informed that his add-on is included or updated on this website (cf. @josephsl's comment)
Thus the community website can become like https://nvda-addons.org.

Personally, I have no strong opinion if this evolution should be confirmed or not. But I think that it is more than a question regarding NVDA remote add-on.
Thus, it would be advisable to bring this topic further on a more general public place, e.g. NVDA add-on mailing list. And according to the decision that is made, update the community website to state more clearly that add-ons may be added on anybody's request and inform nvda-addons mailing list of this new process.

**Comment by nvdaes** [comment]
I agree with @CyrilleB79. I cannot find a PR where @feerrenrut, if I'm remembering correctly, commented that he didn't know what to do since it was created by a person who was not the author of the add-on. And for me Google has automated procedures and we are humans in a community where it¡s better to ask when possible.

**Comment by lukaszgo1** [comment]
I really do not understand why the discussion here went in the direction it did:
1. The fact that developers have to update their plugins for NVDA yearly is unfortunate as it is.
2. There is no question that NVDA Remote is one of the most popular and useful plugins
3. We should not expect each and every developer to participate in the community discussion - most of us may simply do not have time for this and we should appreciate that the add-on has been updated in time for the stable release of NVDA

Questioning the fact that @josephsl decided to help here and created a PR which merely updates the version available via add-on Updater is pointless and more importantly directly hurts users. After all what we should care about is user experience - the compatibility breaking releases should be as transparent for them as possible.

Also this PR is just an update to an existing add-on. If @nvdaes or someone else believes that it should not be exposed via add-on updater than this is not a right place to talk about it. Likewise the comment by @CyrilleB79  where they tried to discuss what rules should be followed for adding new add-ons to the website is irrelevant here as this PR is just an update to the latest version and does not make any breaking change to the process of publishing new add-ons on the add-ons page.

**Review by lukaszgo1 — APPROVED** [review]

**Comment by nvdaes** [comment]
Hello, I think that this add-on should be exposed to add-on updater, and also other ones not included, since addonUpdater is the best option to update add-ons at this moment.
Also, the comment by @CyrilleB79 maybe relevant, not just for new but also for add-ons that need to be updated. The experience of users can also be negatively affected if developers aren't considered before creating pull requests on their behalf. Also, many develpoers cannot participate here, but this PR has been created just a few hours ago. We cannot expect that all developers can join conversation quiclky if we can do it.

**Comment by nvdaes** [comment]
@javidominguez , your opinion sounds good and reasonable for me. I think it's better that authors create PRs, so everybody is sure that authors want to share their work on a particular website.
But of course the license allows to share these add-ons. I think just that we shouldn't be rush, and when possible it's good to mention that authors have been consulted before creating a PR.
I agree with you: we can wait in case authors want to participate, or even try to contact them. And, if in a reasonable time, a week or two, we don't have a response, this PR maybe merged. But we should consider that then other add-ons may be shared on the website without permission. I think that @CyrilleB79 proposal is also reasonable: we can open a discussion about this in other place.

**Comment by CyrilleB79** [comment]
Sorry, I have gone a bit off-topic and should have opened the discussion directly on NVDA add-on mailing list.
The discussion is now opened [here](https://nvda-addons.groups.io/g/nvda-addons/topic/90292015?p=Created,,,100,1,0,0::recentpostdate/sticky,,,100,2,0,90292015,previd=1649312980557394528,nextid=1642932978373992389). Thanks Noelia.

Regarding specifically NVDA remote, to be clear, I confirm that I approve this update.

**Comment by nvdaes** [comment]
@CyrilleB79 , thanks for your opinion. Regarding this PR, obviously I wish that the add-on can be accessible from addonUpdater. Anyway I think that authors should have been contacted (and this should have been mentioned here) before creating this PR. So, as I has formally commented to NV Access, I'm not comfortable approving this PR (and requesting a review from Reef).
Cheers

**Review by tspivey — APPROVED** [review]

**Comment by nvdaes** [comment]
Hello, @tspivey and all: I'm trying to download the add-on without success and I'm getting a message about timeout. I'll approve this PR ASAP and will request a review by Reef.
Thanks

**Review by nvdaes — APPROVED** [review]
I'm approving this after comment by author and downloading the add-on successfully to check the manifest.

**Pull request merged**
