### PR TITLE
Windows Magnifier V1.0

### PR DESCRIPTION
**Pull request by CyrilleB79**
* Add-on name: Windows Magnifier
* Author: Cyrille Bougot
* Version: V1.0
* NVDA compatibility: 2018.3 and beyond (including 2021.1)
* Changes since V1.0-dev-20200306 (version of the community website):
  * Compatibility with NVDA 2021.1
  * A setting panel has been implemented to control more precisely what is reported upon each Magnifier command. Please see the add-on’s documentation for more details.
  * Added a script to toggle cursor restriction
  * Updates according to add-on template
  * Bug fixes
  * The freeze issue that was seen last year does not seem to be present anymore.
* Repo: https://github.com/CyrilleB79/winMag

### CODE REVIEW

**Review by nvdaes — APPROVED** [review]

**Comment by CyrilleB79** [comment]
Since this PR is pending for a week, Windows Magnifier dev version has been able to be tested.
During this test phase, some fixes have been done to documentation and compatibility with older Python 2 release has been restored (commented a dev debug log message using f-string).
I have modified the title and description of this PR and updated the get.php file accordingly.

**Comment by CyrilleB79** [comment]
@nvdaes you may want to review it again.
(I do not know exactly the process)

**Review by nvdaes — APPROVED** [review]
Hello, I've reviewed again manifest and URL and I approve it.

**Comment by CyrilleB79** [comment]
@feerrenrut, I see that you are currently merging PRs in this repo.
The current PR is in conflicted state.
Should I resolve the conflict on my side (but this will dismiss @nvdaes's approval)? Or do you take care of it?

Note: In the future, do you think that it would be useful to add a comment between each `key => value,` line of the get.php file, e.g.:
`# Download links for Windows Magnifier add-on:`
The scope would be to reduce the conflicts that appear regularly when new PR are merged.

**Comment by feerrenrut** [comment]
@CyrilleB79 yes please take care of the conflicts. If there are no other changes since review it won't need to be re-reviewed.

As for comments, I'm happy either way.

**Comment by CyrilleB79** [comment]
Conflict fixed. You can merge. Thanks.

Regarding the comments to avoid frequent merge conflicts, I will open an issue, not a PR since:
* I do not know PHP at all
* overall I have no way to test that the file still works

**Comment by CyrilleB79** [comment]
Uh. I just realize that there is no possibility to open issues in this repo.

Please take https://github.com/nvaccess/addonFiles/pull/97#issuecomment-864875282 in consideration if you feel it is worth.

I think this would be really useful since PRs in this repo are not looked at so frequently. A bunch of PRs have been merged today but the previous series of PRs to be merged was 20 days ago. IMO this frequency is already too low, especially in this breaking compa phase.
If a PR is still blocked during another three weeks just due to merge conflict without any difficulty, I feel it's really a pity.

**Comment by XLTechie** [comment]
Cyrille Bougot wrote:

> Note: In the future, do you think that it would be useful to add a comment between each key => value, line of the get.php file, e.g.:
> # Download links for Windows Magnifier add-on:
> The scope would be to reduce the conflicts that appear regularly when new PR are merged.

How exactly would it do that?

**Review by feerrenrut — APPROVED** [review]

**Pull request merged**
